/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.AbsenceUpdate
import org.openapitools.client.models.AbsenceStatus
import org.openapitools.client.models.AbsenceType

class AbsenceUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AbsenceUpdate
        //val modelInstance = AbsenceUpdate()

        // to test the property `absenceType` - One of \"vacation\", \"sick\", \"sabbatical\", \"parental\", \"other\".
        should("test absenceType") {
            // uncomment below to test the property
            //modelInstance.absenceType shouldBe ("TODO")
        }

        // to test the property `approvedAt`
        should("test approvedAt") {
            // uncomment below to test the property
            //modelInstance.approvedAt shouldBe ("TODO")
        }

        // to test the property `approvedBy` - References the user entity.
        should("test approvedBy") {
            // uncomment below to test the property
            //modelInstance.approvedBy shouldBe ("TODO")
        }

        // to test the property `employeeId` - References the employee entity.
        should("test employeeId") {
            // uncomment below to test the property
            //modelInstance.employeeId shouldBe ("TODO")
        }

        // to test the property `endDate`
        should("test endDate") {
            // uncomment below to test the property
            //modelInstance.endDate shouldBe ("TODO")
        }

        // to test the property `notes`
        should("test notes") {
            // uncomment below to test the property
            //modelInstance.notes shouldBe ("TODO")
        }

        // to test the property `startDate`
        should("test startDate") {
            // uncomment below to test the property
            //modelInstance.startDate shouldBe ("TODO")
        }

        // to test the property `status` - One of \"pending\", \"approved\", \"rejected\", \"cancelled\".
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
