/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Address

class AddressTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Address
        //val modelInstance = Address()

        // to test the property `city`
        should("test city") {
            // uncomment below to test the property
            //modelInstance.city shouldBe ("TODO")
        }

        // to test the property `country` - ISO 3166-1 alpha-2 country code (e.g. \"DE\", \"PL\", \"FR\").
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `street`
        should("test street") {
            // uncomment below to test the property
            //modelInstance.street shouldBe ("TODO")
        }

        // to test the property `streetNumber`
        should("test streetNumber") {
            // uncomment below to test the property
            //modelInstance.streetNumber shouldBe ("TODO")
        }

        // to test the property `zip`
        should("test zip") {
            // uncomment below to test the property
            //modelInstance.zip shouldBe ("TODO")
        }

        // to test the property `company`
        should("test company") {
            // uncomment below to test the property
            //modelInstance.company shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `phone`
        should("test phone") {
            // uncomment below to test the property
            //modelInstance.phone shouldBe ("TODO")
        }

    }
}
