/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.AnlageSErgebnis
import org.openapitools.client.models.AnlageSKfzHinweis

class AnlageSErgebnisTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AnlageSErgebnis
        //val modelInstance = AnlageSErgebnis()

        // to test the property `gewinnVerlust`
        should("test gewinnVerlust") {
            // uncomment below to test the property
            //modelInstance.gewinnVerlust shouldBe ("TODO")
        }

        // to test the property `jahr`
        should("test jahr") {
            // uncomment below to test the property
            //modelInstance.jahr shouldBe ("TODO")
        }

        // to test the property `kfzHinweise`
        should("test kfzHinweise") {
            // uncomment below to test the property
            //modelInstance.kfzHinweise shouldBe ("TODO")
        }

    }
}
