/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.BWARevenue
import org.openapitools.client.models.RevenueItem

class BWARevenueTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BWARevenue
        //val modelInstance = BWARevenue()

        // to test the property `revenueBreakdown`
        should("test revenueBreakdown") {
            // uncomment below to test the property
            //modelInstance.revenueBreakdown shouldBe ("TODO")
        }

        // to test the property `totalRevenue`
        should("test totalRevenue") {
            // uncomment below to test the property
            //modelInstance.totalRevenue shouldBe ("TODO")
        }

    }
}
