/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CategoryTotal

class CategoryTotalTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CategoryTotal
        //val modelInstance = CategoryTotal()

        // to test the property `categoryId`
        should("test categoryId") {
            // uncomment below to test the property
            //modelInstance.categoryId shouldBe ("TODO")
        }

        // to test the property `sharePct`
        should("test sharePct") {
            // uncomment below to test the property
            //modelInstance.sharePct shouldBe ("TODO")
        }

        // to test the property `tco2e`
        should("test tco2e") {
            // uncomment below to test the property
            //modelInstance.tco2e shouldBe ("TODO")
        }

    }
}
