/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CreateShipmentRequest

class CreateShipmentRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateShipmentRequest
        //val modelInstance = CreateShipmentRequest()

        // to test the property `carrier` - Carrier name as configured in shipping settings: `ups` or `dhl`.
        should("test carrier") {
            // uncomment below to test the property
            //modelInstance.carrier shouldBe ("TODO")
        }

        // to test the property `service`
        should("test service") {
            // uncomment below to test the property
            //modelInstance.service shouldBe ("TODO")
        }

        // to test the property `weightKg`
        should("test weightKg") {
            // uncomment below to test the property
            //modelInstance.weightKg shouldBe ("TODO")
        }

    }
}
