/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CreateEmissionTarget

class CreateEmissionTargetTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateEmissionTarget
        //val modelInstance = CreateEmissionTarget()

        // to test the property `baseValue`
        should("test baseValue") {
            // uncomment below to test the property
            //modelInstance.baseValue shouldBe ("TODO")
        }

        // to test the property `baseYear`
        should("test baseYear") {
            // uncomment below to test the property
            //modelInstance.baseYear shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `scope`
        should("test scope") {
            // uncomment below to test the property
            //modelInstance.scope shouldBe ("TODO")
        }

        // to test the property `targetValue`
        should("test targetValue") {
            // uncomment below to test the property
            //modelInstance.targetValue shouldBe ("TODO")
        }

        // to test the property `targetYear`
        should("test targetYear") {
            // uncomment below to test the property
            //modelInstance.targetYear shouldBe ("TODO")
        }

    }
}
