/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CustomerCommunicationUpdate
import org.openapitools.client.models.CommunicationChannel
import org.openapitools.client.models.CommunicationDirection

class CustomerCommunicationUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CustomerCommunicationUpdate
        //val modelInstance = CustomerCommunicationUpdate()

        // to test the property `body` - The message body, call summary or note text.
        should("test body") {
            // uncomment below to test the property
            //modelInstance.body shouldBe ("TODO")
        }

        // to test the property `channel`
        should("test channel") {
            // uncomment below to test the property
            //modelInstance.channel shouldBe ("TODO")
        }

        // to test the property `contactId` - The contact (customer/supplier) this communication belongs to. References the contact entity.
        should("test contactId") {
            // uncomment below to test the property
            //modelInstance.contactId shouldBe ("TODO")
        }

        // to test the property `counterparty` - Email/phone of the counterparty, if applicable.
        should("test counterparty") {
            // uncomment below to test the property
            //modelInstance.counterparty shouldBe ("TODO")
        }

        // to test the property `direction`
        should("test direction") {
            // uncomment below to test the property
            //modelInstance.direction shouldBe ("TODO")
        }

        // to test the property `occurredAt` - When the communication happened (defaults to now on create).
        should("test occurredAt") {
            // uncomment below to test the property
            //modelInstance.occurredAt shouldBe ("TODO")
        }

        // to test the property `subject`
        should("test subject") {
            // uncomment below to test the property
            //modelInstance.subject shouldBe ("TODO")
        }

        // to test the property `tags` - Free-form tags, e.g. `[\"follow-up-required\"]`.
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

    }
}
