/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.EuerDetailErgebnis
import org.openapitools.client.models.EuerZeileDetail

class EuerDetailErgebnisTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EuerDetailErgebnis
        //val modelInstance = EuerDetailErgebnis()

        // to test the property `jahr`
        should("test jahr") {
            // uncomment below to test the property
            //modelInstance.jahr shouldBe ("TODO")
        }

        // to test the property `zeilen`
        should("test zeilen") {
            // uncomment below to test the property
            //modelInstance.zeilen shouldBe ("TODO")
        }

    }
}
