/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GewinnverwendungsReport
import org.openapitools.client.models.GewinnverwendungsZeile

class GewinnverwendungsReportTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GewinnverwendungsReport
        //val modelInstance = GewinnverwendungsReport()

        // to test the property `bilanzgewinn` - Bilanzgewinn nach Einstellung (§ 174 AktG, Beschluss der HV).
        should("test bilanzgewinn") {
            // uncomment below to test the property
            //modelInstance.bilanzgewinn shouldBe ("TODO")
        }

        // to test the property `gesetzlicheRuecklageBestand`
        should("test gesetzlicheRuecklageBestand") {
            // uncomment below to test the property
            //modelInstance.gesetzlicheRuecklageBestand shouldBe ("TODO")
        }

        // to test the property `gesetzlicheRuecklageCap` - Deckel: 10 % des Grundkapitals (§ 150 Abs. 2 AktG).
        should("test gesetzlicheRuecklageCap") {
            // uncomment below to test the property
            //modelInstance.gesetzlicheRuecklageCap shouldBe ("TODO")
        }

        // to test the property `gesetzlicheRuecklageNach` - Rücklage nach Einstellung.
        should("test gesetzlicheRuecklageNach") {
            // uncomment below to test the property
            //modelInstance.gesetzlicheRuecklageNach shouldBe ("TODO")
        }

        // to test the property `gesetzlicheRuecklageSoll` - Vorgeschlagene Einstellung in die gesetzliche Rücklage (§ 150 Abs. 2 AktG).
        should("test gesetzlicheRuecklageSoll") {
            // uncomment below to test the property
            //modelInstance.gesetzlicheRuecklageSoll shouldBe ("TODO")
        }

        // to test the property `gezeichnetesKapital`
        should("test gezeichnetesKapital") {
            // uncomment below to test the property
            //modelInstance.gezeichnetesKapital shouldBe ("TODO")
        }

        // to test the property `jahresueberschuss`
        should("test jahresueberschuss") {
            // uncomment below to test the property
            //modelInstance.jahresueberschuss shouldBe ("TODO")
        }

        // to test the property `year`
        should("test year") {
            // uncomment below to test the property
            //modelInstance.year shouldBe ("TODO")
        }

        // to test the property `zeilen`
        should("test zeilen") {
            // uncomment below to test the property
            //modelInstance.zeilen shouldBe ("TODO")
        }

    }
}
