/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.InstituteStatus
import org.openapitools.client.models.InstituteCheckItem
import org.openapitools.client.models.InstituteDeadlines

class InstituteStatusTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InstituteStatus
        //val modelInstance = InstituteStatus()

        // to test the property `checklist`
        should("test checklist") {
            // uncomment below to test the property
            //modelInstance.checklist shouldBe ("TODO")
        }

        // to test the property `deadlines`
        should("test deadlines") {
            // uncomment below to test the property
            //modelInstance.deadlines shouldBe ("TODO")
        }

        // to test the property `instituteType`
        should("test instituteType") {
            // uncomment below to test the property
            //modelInstance.instituteType shouldBe ("TODO")
        }

        // to test the property `kapitalmarktorientiert`
        should("test kapitalmarktorientiert") {
            // uncomment below to test the property
            //modelInstance.kapitalmarktorientiert shouldBe ("TODO")
        }

    }
}
