/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.InvoiceCreate
import org.openapitools.client.models.CountryCode
import org.openapitools.client.models.CurrencyCode
import org.openapitools.client.models.DocumentType
import org.openapitools.client.models.InvoiceStatus
import org.openapitools.client.models.InvoiceType
import org.openapitools.client.models.PaymentStatus
import org.openapitools.client.models.PrecedingSalesVoucherType

class InvoiceCreateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvoiceCreate
        //val modelInstance = InvoiceCreate()

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `invoiceType`
        should("test invoiceType") {
            // uncomment below to test the property
            //modelInstance.invoiceType shouldBe ("TODO")
        }

        // to test the property `issueDate`
        should("test issueDate") {
            // uncomment below to test the property
            //modelInstance.issueDate shouldBe ("TODO")
        }

        // to test the property `lineItems`
        should("test lineItems") {
            // uncomment below to test the property
            //modelInstance.lineItems shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `subtotal`
        should("test subtotal") {
            // uncomment below to test the property
            //modelInstance.subtotal shouldBe ("TODO")
        }

        // to test the property `totalAmount`
        should("test totalAmount") {
            // uncomment below to test the property
            //modelInstance.totalAmount shouldBe ("TODO")
        }

        // to test the property `totalTax`
        should("test totalTax") {
            // uncomment below to test the property
            //modelInstance.totalTax shouldBe ("TODO")
        }

        // to test the property `attachments`
        should("test attachments") {
            // uncomment below to test the property
            //modelInstance.attachments shouldBe ("TODO")
        }

        // to test the property `billingPeriodEnd`
        should("test billingPeriodEnd") {
            // uncomment below to test the property
            //modelInstance.billingPeriodEnd shouldBe ("TODO")
        }

        // to test the property `billingPeriodStart`
        should("test billingPeriodStart") {
            // uncomment below to test the property
            //modelInstance.billingPeriodStart shouldBe ("TODO")
        }

        // to test the property `cancellationDate`
        should("test cancellationDate") {
            // uncomment below to test the property
            //modelInstance.cancellationDate shouldBe ("TODO")
        }

        // to test the property `cancellationInvoiceId` - References the invoice entity.
        should("test cancellationInvoiceId") {
            // uncomment below to test the property
            //modelInstance.cancellationInvoiceId shouldBe ("TODO")
        }

        // to test the property `cancellationReason`
        should("test cancellationReason") {
            // uncomment below to test the property
            //modelInstance.cancellationReason shouldBe ("TODO")
        }

        // to test the property `contractId` - References the contract entity.
        should("test contractId") {
            // uncomment below to test the property
            //modelInstance.contractId shouldBe ("TODO")
        }

        // to test the property `customerId` - References the customer entity.
        should("test customerId") {
            // uncomment below to test the property
            //modelInstance.customerId shouldBe ("TODO")
        }

        // to test the property `discountAmount`
        should("test discountAmount") {
            // uncomment below to test the property
            //modelInstance.discountAmount shouldBe ("TODO")
        }

        // to test the property `discountDays`
        should("test discountDays") {
            // uncomment below to test the property
            //modelInstance.discountDays shouldBe ("TODO")
        }

        // to test the property `discountPercentage`
        should("test discountPercentage") {
            // uncomment below to test the property
            //modelInstance.discountPercentage shouldBe ("TODO")
        }

        // to test the property `documentType`
        should("test documentType") {
            // uncomment below to test the property
            //modelInstance.documentType shouldBe ("TODO")
        }

        // to test the property `dunningLevel`
        should("test dunningLevel") {
            // uncomment below to test the property
            //modelInstance.dunningLevel shouldBe ("TODO")
        }

        // to test the property `inputVatAmount`
        should("test inputVatAmount") {
            // uncomment below to test the property
            //modelInstance.inputVatAmount shouldBe ("TODO")
        }

        // to test the property `inputVatDeductible`
        should("test inputVatDeductible") {
            // uncomment below to test the property
            //modelInstance.inputVatDeductible shouldBe ("TODO")
        }

        // to test the property `inputVatPercentage`
        should("test inputVatPercentage") {
            // uncomment below to test the property
            //modelInstance.inputVatPercentage shouldBe ("TODO")
        }

        // to test the property `introductionText`
        should("test introductionText") {
            // uncomment below to test the property
            //modelInstance.introductionText shouldBe ("TODO")
        }

        // to test the property `isCancelled`
        should("test isCancelled") {
            // uncomment below to test the property
            //modelInstance.isCancelled shouldBe ("TODO")
        }

        // to test the property `isDraft`
        should("test isDraft") {
            // uncomment below to test the property
            //modelInstance.isDraft shouldBe ("TODO")
        }

        // to test the property `isEuAcquisition`
        should("test isEuAcquisition") {
            // uncomment below to test the property
            //modelInstance.isEuAcquisition shouldBe ("TODO")
        }

        // to test the property `isEuDelivery`
        should("test isEuDelivery") {
            // uncomment below to test the property
            //modelInstance.isEuDelivery shouldBe ("TODO")
        }

        // to test the property `isIntraCommunityAcquisition`
        should("test isIntraCommunityAcquisition") {
            // uncomment below to test the property
            //modelInstance.isIntraCommunityAcquisition shouldBe ("TODO")
        }

        // to test the property `isReverseCharge`
        should("test isReverseCharge") {
            // uncomment below to test the property
            //modelInstance.isReverseCharge shouldBe ("TODO")
        }

        // to test the property `ledgerAccount`
        should("test ledgerAccount") {
            // uncomment below to test the property
            //modelInstance.ledgerAccount shouldBe ("TODO")
        }

        // to test the property `margin25a`
        should("test margin25a") {
            // uncomment below to test the property
            //modelInstance.margin25a shouldBe ("TODO")
        }

        // to test the property `margin25aGross`
        should("test margin25aGross") {
            // uncomment below to test the property
            //modelInstance.margin25aGross shouldBe ("TODO")
        }

        // to test the property `margin25aPurchasePrice`
        should("test margin25aPurchasePrice") {
            // uncomment below to test the property
            //modelInstance.margin25aPurchasePrice shouldBe ("TODO")
        }

        // to test the property `notes`
        should("test notes") {
            // uncomment below to test the property
            //modelInstance.notes shouldBe ("TODO")
        }

        // to test the property `orderNumber`
        should("test orderNumber") {
            // uncomment below to test the property
            //modelInstance.orderNumber shouldBe ("TODO")
        }

        // to test the property `originalPdfPath`
        should("test originalPdfPath") {
            // uncomment below to test the property
            //modelInstance.originalPdfPath shouldBe ("TODO")
        }

        // to test the property `paidAmount`
        should("test paidAmount") {
            // uncomment below to test the property
            //modelInstance.paidAmount shouldBe ("TODO")
        }

        // to test the property `paymentDueDate`
        should("test paymentDueDate") {
            // uncomment below to test the property
            //modelInstance.paymentDueDate shouldBe ("TODO")
        }

        // to test the property `paymentStatus`
        should("test paymentStatus") {
            // uncomment below to test the property
            //modelInstance.paymentStatus shouldBe ("TODO")
        }

        // to test the property `paymentTermsText`
        should("test paymentTermsText") {
            // uncomment below to test the property
            //modelInstance.paymentTermsText shouldBe ("TODO")
        }

        // to test the property `precedingSalesVoucherId` - References the preceding sales voucher entity.
        should("test precedingSalesVoucherId") {
            // uncomment below to test the property
            //modelInstance.precedingSalesVoucherId shouldBe ("TODO")
        }

        // to test the property `precedingSalesVoucherType`
        should("test precedingSalesVoucherType") {
            // uncomment below to test the property
            //modelInstance.precedingSalesVoucherType shouldBe ("TODO")
        }

        // to test the property `receiptConfirmationAvailable`
        should("test receiptConfirmationAvailable") {
            // uncomment below to test the property
            //modelInstance.receiptConfirmationAvailable shouldBe ("TODO")
        }

        // to test the property `relatedInvoiceId` - References the invoice entity.
        should("test relatedInvoiceId") {
            // uncomment below to test the property
            //modelInstance.relatedInvoiceId shouldBe ("TODO")
        }

        // to test the property `relationshipType`
        should("test relationshipType") {
            // uncomment below to test the property
            //modelInstance.relationshipType shouldBe ("TODO")
        }

        // to test the property `senderSnapshot`
        should("test senderSnapshot") {
            // uncomment below to test the property
            //modelInstance.senderSnapshot shouldBe ("TODO")
        }

        // to test the property `sentAt`
        should("test sentAt") {
            // uncomment below to test the property
            //modelInstance.sentAt shouldBe ("TODO")
        }

        // to test the property `servicePeriodEnd`
        should("test servicePeriodEnd") {
            // uncomment below to test the property
            //modelInstance.servicePeriodEnd shouldBe ("TODO")
        }

        // to test the property `servicePeriodStart`
        should("test servicePeriodStart") {
            // uncomment below to test the property
            //modelInstance.servicePeriodStart shouldBe ("TODO")
        }

        // to test the property `supplierId` - References the supplier entity.
        should("test supplierId") {
            // uncomment below to test the property
            //modelInstance.supplierId shouldBe ("TODO")
        }

        // to test the property `taxExemptionReason`
        should("test taxExemptionReason") {
            // uncomment below to test the property
            //modelInstance.taxExemptionReason shouldBe ("TODO")
        }

        // to test the property `vatCountry`
        should("test vatCountry") {
            // uncomment below to test the property
            //modelInstance.vatCountry shouldBe ("TODO")
        }

        // to test the property `vatSpecialCase`
        should("test vatSpecialCase") {
            // uncomment below to test the property
            //modelInstance.vatSpecialCase shouldBe ("TODO")
        }

    }
}
