/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.KonzernExportResponse

class KonzernExportResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of KonzernExportResponse
        //val modelInstance = KonzernExportResponse()

        // to test the property `csvContent`
        should("test csvContent") {
            // uncomment below to test the property
            //modelInstance.csvContent shouldBe ("TODO")
        }

        // to test the property `filename`
        should("test filename") {
            // uncomment below to test the property
            //modelInstance.filename shouldBe ("TODO")
        }

    }
}
