/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PayrollSummaryItem
import org.openapitools.client.models.PayrollRunStatus

class PayrollSummaryItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PayrollSummaryItem
        //val modelInstance = PayrollSummaryItem()

        // to test the property `employeeCount`
        should("test employeeCount") {
            // uncomment below to test the property
            //modelInstance.employeeCount shouldBe ("TODO")
        }

        // to test the property `month`
        should("test month") {
            // uncomment below to test the property
            //modelInstance.month shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `totalEmployerCost`
        should("test totalEmployerCost") {
            // uncomment below to test the property
            //modelInstance.totalEmployerCost shouldBe ("TODO")
        }

        // to test the property `totalGross`
        should("test totalGross") {
            // uncomment below to test the property
            //modelInstance.totalGross shouldBe ("TODO")
        }

        // to test the property `totalNet`
        should("test totalNet") {
            // uncomment below to test the property
            //modelInstance.totalNet shouldBe ("TODO")
        }

        // to test the property `year`
        should("test year") {
            // uncomment below to test the property
            //modelInstance.year shouldBe ("TODO")
        }

    }
}
