/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PriceTier

class PriceTierTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PriceTier
        //val modelInstance = PriceTier()

        // to test the property `productId` - References the product entity.
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `unitPrice` - Net unit price once `min_quantity` is reached.
        should("test unitPrice") {
            // uncomment below to test the property
            //modelInstance.unitPrice shouldBe ("TODO")
        }

        // to test the property `customerGroupId` - None = tier applies to all customers; otherwise a customer group id.
        should("test customerGroupId") {
            // uncomment below to test the property
            //modelInstance.customerGroupId shouldBe ("TODO")
        }

        // to test the property `minQuantity` - Quantity from which this tier applies (inclusive).
        should("test minQuantity") {
            // uncomment below to test the property
            //modelInstance.minQuantity shouldBe ("TODO")
        }

    }
}
