/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ProductAttributeUpdate

class ProductAttributeUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductAttributeUpdate
        //val modelInstance = ProductAttributeUpdate()

        // to test the property `isFilterable` - Whether this attribute participates in the shop's faceted filters.
        should("test isFilterable") {
            // uncomment below to test the property
            //modelInstance.isFilterable shouldBe ("TODO")
        }

        // to test the property `name` - Attribute name, e.g. `Material`, `Farbe`, `Gewicht`.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `position` - Ordering position within the product's attribute list.
        should("test position") {
            // uncomment below to test the property
            //modelInstance.position shouldBe ("TODO")
        }

        // to test the property `productId` - The product this attribute belongs to. References the product entity.
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `unit` - Optional unit of measure for numeric attributes, e.g. `g`, `cm`.
        should("test unit") {
            // uncomment below to test the property
            //modelInstance.unit shouldBe ("TODO")
        }

        // to test the property ``value`` - Attribute value, e.g. `Baumwolle`, `Rot`, `180g`.
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

    }
}
