/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ProposedAssignment

class ProposedAssignmentTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProposedAssignment
        //val modelInstance = ProposedAssignment()

        // to test the property `amountPaid`
        should("test amountPaid") {
            // uncomment below to test the property
            //modelInstance.amountPaid shouldBe ("TODO")
        }

        // to test the property `confidence`
        should("test confidence") {
            // uncomment below to test the property
            //modelInstance.confidence shouldBe ("TODO")
        }

        // to test the property `invoiceId`
        should("test invoiceId") {
            // uncomment below to test the property
            //modelInstance.invoiceId shouldBe ("TODO")
        }

        // to test the property `invoiceNumber`
        should("test invoiceNumber") {
            // uncomment below to test the property
            //modelInstance.invoiceNumber shouldBe ("TODO")
        }

        // to test the property `openAmount`
        should("test openAmount") {
            // uncomment below to test the property
            //modelInstance.openAmount shouldBe ("TODO")
        }

        // to test the property `paymentDate`
        should("test paymentDate") {
            // uncomment below to test the property
            //modelInstance.paymentDate shouldBe ("TODO")
        }

        // to test the property `paymentId`
        should("test paymentId") {
            // uncomment below to test the property
            //modelInstance.paymentId shouldBe ("TODO")
        }

        // to test the property `reason`
        should("test reason") {
            // uncomment below to test the property
            //modelInstance.reason shouldBe ("TODO")
        }

        // to test the property `customerId`
        should("test customerId") {
            // uncomment below to test the property
            //modelInstance.customerId shouldBe ("TODO")
        }

        // to test the property `reference`
        should("test reference") {
            // uncomment below to test the property
            //modelInstance.reference shouldBe ("TODO")
        }

    }
}
