/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PublicDeliveryAppointmentRequest

class PublicDeliveryAppointmentRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PublicDeliveryAppointmentRequest
        //val modelInstance = PublicDeliveryAppointmentRequest()

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `requestedDate`
        should("test requestedDate") {
            // uncomment below to test the property
            //modelInstance.requestedDate shouldBe ("TODO")
        }

        // to test the property `supplierName`
        should("test supplierName") {
            // uncomment below to test the property
            //modelInstance.supplierName shouldBe ("TODO")
        }

        // to test the property `warehouseCode` - Warehouse `code` — the supplier does not know the warehouse uuid.
        should("test warehouseCode") {
            // uncomment below to test the property
            //modelInstance.warehouseCode shouldBe ("TODO")
        }

        // to test the property `notes`
        should("test notes") {
            // uncomment below to test the property
            //modelInstance.notes shouldBe ("TODO")
        }

        // to test the property `timeSlot`
        should("test timeSlot") {
            // uncomment below to test the property
            //modelInstance.timeSlot shouldBe ("TODO")
        }

    }
}
