/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.QuartileBand

class QuartileBandTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QuartileBand
        //val modelInstance = QuartileBand()

        // to test the property `femaleSharePct`
        should("test femaleSharePct") {
            // uncomment below to test the property
            //modelInstance.femaleSharePct shouldBe ("TODO")
        }

        // to test the property `hourlyMedian`
        should("test hourlyMedian") {
            // uncomment below to test the property
            //modelInstance.hourlyMedian shouldBe ("TODO")
        }

        // to test the property `maleSharePct`
        should("test maleSharePct") {
            // uncomment below to test the property
            //modelInstance.maleSharePct shouldBe ("TODO")
        }

        // to test the property `quartile`
        should("test quartile") {
            // uncomment below to test the property
            //modelInstance.quartile shouldBe ("TODO")
        }

    }
}
