/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ServiceJobCreate
import org.openapitools.client.models.ServiceJobStatus

class ServiceJobCreateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ServiceJobCreate
        //val modelInstance = ServiceJobCreate()

        // to test the property `address` - Street + zip + city of the job location.
        should("test address") {
            // uncomment below to test the property
            //modelInstance.address shouldBe ("TODO")
        }

        // to test the property `customerEmail` - Customer email for email notifications.
        should("test customerEmail") {
            // uncomment below to test the property
            //modelInstance.customerEmail shouldBe ("TODO")
        }

        // to test the property `customerId` - References the customer entity.
        should("test customerId") {
            // uncomment below to test the property
            //modelInstance.customerId shouldBe ("TODO")
        }

        // to test the property `customerName` - Denormalized customer name for quick display.
        should("test customerName") {
            // uncomment below to test the property
            //modelInstance.customerName shouldBe ("TODO")
        }

        // to test the property `customerPhone` - Customer phone for SMS notifications later.
        should("test customerPhone") {
            // uncomment below to test the property
            //modelInstance.customerPhone shouldBe ("TODO")
        }

        // to test the property `description` - What work needs to be done.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `estimatedDurationMinutes` - Estimated time for the job in minutes.
        should("test estimatedDurationMinutes") {
            // uncomment below to test the property
            //modelInstance.estimatedDurationMinutes shouldBe ("TODO")
        }

        // to test the property `lat` - Latitude for map display (OpenStreetMap).
        should("test lat") {
            // uncomment below to test the property
            //modelInstance.lat shouldBe ("TODO")
        }

        // to test the property `lng` - Longitude for map display (OpenStreetMap).
        should("test lng") {
            // uncomment below to test the property
            //modelInstance.lng shouldBe ("TODO")
        }

        // to test the property `notes`
        should("test notes") {
            // uncomment below to test the property
            //modelInstance.notes shouldBe ("TODO")
        }

        // to test the property `status` - Dispatch status: \"pending\", \"assigned\", \"en_route\", \"in_progress\", \"completed\", \"cancelled\".
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
