/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SmtpConfig
import org.openapitools.client.models.SmtpEncryption

class SmtpConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SmtpConfig
        //val modelInstance = SmtpConfig()

        // to test the property `encryption`
        should("test encryption") {
            // uncomment below to test the property
            //modelInstance.encryption shouldBe ("TODO")
        }

        // to test the property `fromAddress`
        should("test fromAddress") {
            // uncomment below to test the property
            //modelInstance.fromAddress shouldBe ("TODO")
        }

        // to test the property `host`
        should("test host") {
            // uncomment below to test the property
            //modelInstance.host shouldBe ("TODO")
        }

        // to test the property `password`
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

        // to test the property `port`
        should("test port") {
            // uncomment below to test the property
            //modelInstance.port shouldBe ("TODO")
        }

        // to test the property `username`
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `fromName`
        should("test fromName") {
            // uncomment below to test the property
            //modelInstance.fromName shouldBe ("TODO")
        }

        // to test the property `timeoutSeconds`
        should("test timeoutSeconds") {
            // uncomment below to test the property
            //modelInstance.timeoutSeconds shouldBe ("TODO")
        }

    }
}
