/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StillePartnerZeile

class StillePartnerZeileTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StillePartnerZeile
        //val modelInstance = StillePartnerZeile()

        // to test the property `auseinandersetzungsguthaben`
        should("test auseinandersetzungsguthaben") {
            // uncomment below to test the property
            //modelInstance.auseinandersetzungsguthaben shouldBe ("TODO")
        }

        // to test the property `gewinnanteil`
        should("test gewinnanteil") {
            // uncomment below to test the property
            //modelInstance.gewinnanteil shouldBe ("TODO")
        }

        // to test the property `gewinnvortrag`
        should("test gewinnvortrag") {
            // uncomment below to test the property
            //modelInstance.gewinnvortrag shouldBe ("TODO")
        }

        // to test the property `instrumentType`
        should("test instrumentType") {
            // uncomment below to test the property
            //modelInstance.instrumentType shouldBe ("TODO")
        }

        // to test the property `kest`
        should("test kest") {
            // uncomment below to test the property
            //modelInstance.kest shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `verlustVerrechnungskonto`
        should("test verlustVerrechnungskonto") {
            // uncomment below to test the property
            //modelInstance.verlustVerrechnungskonto shouldBe ("TODO")
        }

        // to test the property `verlustanteil`
        should("test verlustanteil") {
            // uncomment below to test the property
            //modelInstance.verlustanteil shouldBe ("TODO")
        }

        // to test the property `hinweis`
        should("test hinweis") {
            // uncomment below to test the property
            //modelInstance.hinweis shouldBe ("TODO")
        }

    }
}
