/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SuitabilityResult
import org.openapitools.client.models.BoxFit
import org.openapitools.client.models.MethodSuitability

class SuitabilityResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SuitabilityResult
        //val modelInstance = SuitabilityResult()

        // to test the property `methods`
        should("test methods") {
            // uncomment below to test the property
            //modelInstance.methods shouldBe ("TODO")
        }

        // to test the property `requiresInsurance`
        should("test requiresInsurance") {
            // uncomment below to test the property
            //modelInstance.requiresInsurance shouldBe ("TODO")
        }

        // to test the property `totalValue`
        should("test totalValue") {
            // uncomment below to test the property
            //modelInstance.totalValue shouldBe ("TODO")
        }

        // to test the property `totalWeightKg`
        should("test totalWeightKg") {
            // uncomment below to test the property
            //modelInstance.totalWeightKg shouldBe ("TODO")
        }

        // to test the property `recommendedBox`
        should("test recommendedBox") {
            // uncomment below to test the property
            //modelInstance.recommendedBox shouldBe ("TODO")
        }

    }
}
