/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SupplierInvoice
import org.openapitools.client.models.SupplierInvoiceStatus

class SupplierInvoiceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SupplierInvoice
        //val modelInstance = SupplierInvoice()

        // to test the property `invoiceDate`
        should("test invoiceDate") {
            // uncomment below to test the property
            //modelInstance.invoiceDate shouldBe ("TODO")
        }

        // to test the property `invoiceNumber`
        should("test invoiceNumber") {
            // uncomment below to test the property
            //modelInstance.invoiceNumber shouldBe ("TODO")
        }

        // to test the property `lineItems` - JSON array of `{product_id, name, quantity, unitPriceNet, taxRate}`.
        should("test lineItems") {
            // uncomment below to test the property
            //modelInstance.lineItems shouldBe ("TODO")
        }

        // to test the property `status` - One of: draft | matched | has_variances | posted | cancelled
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `goodsReceiptId` - References the goods receipt entity.
        should("test goodsReceiptId") {
            // uncomment below to test the property
            //modelInstance.goodsReceiptId shouldBe ("TODO")
        }

        // to test the property `notes`
        should("test notes") {
            // uncomment below to test the property
            //modelInstance.notes shouldBe ("TODO")
        }

        // to test the property `purchaseOrderId` - References the purchase order entity.
        should("test purchaseOrderId") {
            // uncomment below to test the property
            //modelInstance.purchaseOrderId shouldBe ("TODO")
        }

        // to test the property `supplierContactId` - References the supplier entity.
        should("test supplierContactId") {
            // uncomment below to test the property
            //modelInstance.supplierContactId shouldBe ("TODO")
        }

        // to test the property `supplierName`
        should("test supplierName") {
            // uncomment below to test the property
            //modelInstance.supplierName shouldBe ("TODO")
        }

        // to test the property `totalGrossAmount`
        should("test totalGrossAmount") {
            // uncomment below to test the property
            //modelInstance.totalGrossAmount shouldBe ("TODO")
        }

        // to test the property `totalNetAmount`
        should("test totalNetAmount") {
            // uncomment below to test the property
            //modelInstance.totalNetAmount shouldBe ("TODO")
        }

    }
}
