/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TicketMessage
import org.openapitools.client.models.MessageDirection
import org.openapitools.client.models.MessageType

class TicketMessageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TicketMessage
        //val modelInstance = TicketMessage()

        // to test the property `body`
        should("test body") {
            // uncomment below to test the property
            //modelInstance.body shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `direction`
        should("test direction") {
            // uncomment below to test the property
            //modelInstance.direction shouldBe ("TODO")
        }

        // to test the property `isInternal`
        should("test isInternal") {
            // uncomment below to test the property
            //modelInstance.isInternal shouldBe ("TODO")
        }

        // to test the property `messageType`
        should("test messageType") {
            // uncomment below to test the property
            //modelInstance.messageType shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `tenantId`
        should("test tenantId") {
            // uncomment below to test the property
            //modelInstance.tenantId shouldBe ("TODO")
        }

        // to test the property `ticketId` - References the ticket entity.
        should("test ticketId") {
            // uncomment below to test the property
            //modelInstance.ticketId shouldBe ("TODO")
        }

        // to test the property `authorEmail`
        should("test authorEmail") {
            // uncomment below to test the property
            //modelInstance.authorEmail shouldBe ("TODO")
        }

        // to test the property `authorName`
        should("test authorName") {
            // uncomment below to test the property
            //modelInstance.authorName shouldBe ("TODO")
        }

        // to test the property `bodyHtml`
        should("test bodyHtml") {
            // uncomment below to test the property
            //modelInstance.bodyHtml shouldBe ("TODO")
        }

        // to test the property `channelId`
        should("test channelId") {
            // uncomment below to test the property
            //modelInstance.channelId shouldBe ("TODO")
        }

        // to test the property `externalId`
        should("test externalId") {
            // uncomment below to test the property
            //modelInstance.externalId shouldBe ("TODO")
        }

    }
}
