/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TrackOrderResponse
import org.openapitools.client.models.TrackedShipment

class TrackOrderResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TrackOrderResponse
        //val modelInstance = TrackOrderResponse()

        // to test the property `orderNumber`
        should("test orderNumber") {
            // uncomment below to test the property
            //modelInstance.orderNumber shouldBe ("TODO")
        }

        // to test the property `orderStatus`
        should("test orderStatus") {
            // uncomment below to test the property
            //modelInstance.orderStatus shouldBe ("TODO")
        }

        // to test the property `shipments`
        should("test shipments") {
            // uncomment below to test the property
            //modelInstance.shipments shouldBe ("TODO")
        }

    }
}
