/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.UserTenantInfo

class UserTenantInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserTenantInfo
        //val modelInstance = UserTenantInfo()

        // to test the property `role`
        should("test role") {
            // uncomment below to test the property
            //modelInstance.role shouldBe ("TODO")
        }

        // to test the property `tenantId`
        should("test tenantId") {
            // uncomment below to test the property
            //modelInstance.tenantId shouldBe ("TODO")
        }

        // to test the property `tenantName`
        should("test tenantName") {
            // uncomment below to test the property
            //modelInstance.tenantName shouldBe ("TODO")
        }

        // to test the property `customDomain`
        should("test customDomain") {
            // uncomment below to test the property
            //modelInstance.customDomain shouldBe ("TODO")
        }

        // to test the property `subdomain`
        should("test subdomain") {
            // uncomment below to test the property
            //modelInstance.subdomain shouldBe ("TODO")
        }

    }
}
