/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.VatSummary
import org.openapitools.client.models.VatItem

class VatSummaryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VatSummary
        //val modelInstance = VatSummary()

        // to test the property `inputTaxItems`
        should("test inputTaxItems") {
            // uncomment below to test the property
            //modelInstance.inputTaxItems shouldBe ("TODO")
        }

        // to test the property `outputTaxItems`
        should("test outputTaxItems") {
            // uncomment below to test the property
            //modelInstance.outputTaxItems shouldBe ("TODO")
        }

        // to test the property `totalInputTax`
        should("test totalInputTax") {
            // uncomment below to test the property
            //modelInstance.totalInputTax shouldBe ("TODO")
        }

        // to test the property `totalOutputTax`
        should("test totalOutputTax") {
            // uncomment below to test the property
            //modelInstance.totalOutputTax shouldBe ("TODO")
        }

        // to test the property `vatDue`
        should("test vatDue") {
            // uncomment below to test the property
            //modelInstance.vatDue shouldBe ("TODO")
        }

    }
}
