/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.DatevImportApi
import org.openapitools.client.models.DatevImportResponse

class DatevImportApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DatevImportApi
        //val apiInstance = DatevImportApi()

        // to test datevImportApi
        should("test datevImportApi") {
            // uncomment below to test datevImportApi
            //val body : kotlin.Any =  // kotlin.Any | 
            //val result : DatevImportResponse = apiInstance.datevImportApi(body)
            //result shouldBe ("TODO")
        }

    }
}
