/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.EbilanzApi
import org.openapitools.client.models.EBilanzReport

class EbilanzApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EbilanzApi
        //val apiInstance = EbilanzApi()

        // to test ebilanzReportApi
        should("test ebilanzReportApi") {
            // uncomment below to test ebilanzReportApi
            //val year : kotlin.Int = 56 // kotlin.Int | 
            //val dateFrom : kotlin.String = dateFrom_example // kotlin.String | 
            //val dateTo : kotlin.String = dateTo_example // kotlin.String | 
            //val result : EBilanzReport = apiInstance.ebilanzReportApi(year, dateFrom, dateTo)
            //result shouldBe ("TODO")
        }

        // to test ebilanzXbrlExportApi
        should("test ebilanzXbrlExportApi") {
            // uncomment below to test ebilanzXbrlExportApi
            //val year : kotlin.Int = 56 // kotlin.Int | 
            //val dateFrom : kotlin.String = dateFrom_example // kotlin.String | 
            //val dateTo : kotlin.String = dateTo_example // kotlin.String | 
            //apiInstance.ebilanzXbrlExportApi(year, dateFrom, dateTo)
        }

    }
}
