/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.GobdExportApi
import org.openapitools.client.models.GoBDExportResponse
import org.openapitools.client.models.PluginError

class GobdExportApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GobdExportApi
        //val apiInstance = GobdExportApi()

        // to test buchhalterCsvApi
        should("test buchhalterCsvApi") {
            // uncomment below to test buchhalterCsvApi
            //val dateFrom : kotlin.String = dateFrom_example // kotlin.String | 
            //val dateTo : kotlin.String = dateTo_example // kotlin.String | 
            //val result : GoBDExportResponse = apiInstance.buchhalterCsvApi(dateFrom, dateTo)
            //result shouldBe ("TODO")
        }

        // to test gobdExportApi
        should("test gobdExportApi") {
            // uncomment below to test gobdExportApi
            //val year : kotlin.Int = 56 // kotlin.Int | 
            //val format : kotlin.String = zip // kotlin.String | Export format: `zip` (default, full GDPdU/IDEA export) or `csv` (legacy single-journal CSV as JSON).
            //apiInstance.gobdExportApi(year, format)
        }

    }
}
