/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.KycRecordApi
import org.openapitools.client.models.KycRecord
import org.openapitools.client.models.KycRecordCreate
import org.openapitools.client.models.KycRecordUpdate
import org.openapitools.client.models.PluginError

class KycRecordApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of KycRecordApi
        //val apiInstance = KycRecordApi()

        // to test createKycRecord
        should("test createKycRecord") {
            // uncomment below to test createKycRecord
            //val kycRecordCreate : KycRecordCreate =  // KycRecordCreate | 
            //val result : KycRecord = apiInstance.createKycRecord(kycRecordCreate)
            //result shouldBe ("TODO")
        }

        // to test deleteKycRecord
        should("test deleteKycRecord") {
            // uncomment below to test deleteKycRecord
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.deleteKycRecord(id)
        }

        // to test getKycRecord
        should("test getKycRecord") {
            // uncomment below to test getKycRecord
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : KycRecord = apiInstance.getKycRecord(id)
            //result shouldBe ("TODO")
        }

        // to test getKycRecords
        should("test getKycRecords") {
            // uncomment below to test getKycRecords
            //val page : kotlin.Int = 1 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val search : kotlin.String = search_example // kotlin.String | 
            //val includeDeleted : kotlin.Boolean = true // kotlin.Boolean | Soft-delete entities: set true to include rows with `deleted_at` set.
            //val result : kotlin.collections.List<KycRecord> = apiInstance.getKycRecords(page, pageSize, search, includeDeleted)
            //result shouldBe ("TODO")
        }

        // to test updateKycRecord
        should("test updateKycRecord") {
            // uncomment below to test updateKycRecord
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val kycRecordUpdate : KycRecordUpdate =  // KycRecordUpdate | 
            //val result : KycRecord = apiInstance.updateKycRecord(id, kycRecordUpdate)
            //result shouldBe ("TODO")
        }

    }
}
