/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.OnlineshopApi
import org.openapitools.client.models.PluginError
import org.openapitools.client.models.SmtpConfig

class OnlineshopApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OnlineshopApi
        //val apiInstance = OnlineshopApi()

        // to test getSmtpConfigApi
        should("test getSmtpConfigApi") {
            // uncomment below to test getSmtpConfigApi
            //val result : SmtpConfig = apiInstance.getSmtpConfigApi()
            //result shouldBe ("TODO")
        }

        // to test saveSmtpConfigApi
        should("test saveSmtpConfigApi") {
            // uncomment below to test saveSmtpConfigApi
            //val smtpConfig : SmtpConfig =  // SmtpConfig | 
            //val result : SmtpConfig = apiInstance.saveSmtpConfigApi(smtpConfig)
            //result shouldBe ("TODO")
        }

    }
}
