/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.OssReportApi
import org.openapitools.client.models.OssReport

class OssReportApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OssReportApi
        //val apiInstance = OssReportApi()

        // to test ossReportApi
        should("test ossReportApi") {
            // uncomment below to test ossReportApi
            //val result : OssReport = apiInstance.ossReportApi()
            //result shouldBe ("TODO")
        }

    }
}
