/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.PosApi
import org.openapitools.client.models.PosRegister
import org.openapitools.client.models.PosRegisterCreate
import org.openapitools.client.models.PosTable
import org.openapitools.client.models.PosTableCreate

class PosApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PosApi
        //val apiInstance = PosApi()

        // to test posBilling
        should("test posBilling") {
            // uncomment below to test posBilling
            //val result : kotlin.Any = apiInstance.posBilling()
            //result shouldBe ("TODO")
        }

        // to test posCreateOrder
        should("test posCreateOrder") {
            // uncomment below to test posCreateOrder
            //val body : kotlin.Any =  // kotlin.Any | 
            //val result : kotlin.Any = apiInstance.posCreateOrder(body)
            //result shouldBe ("TODO")
        }

        // to test posCreateRegister
        should("test posCreateRegister") {
            // uncomment below to test posCreateRegister
            //val posRegisterCreate : PosRegisterCreate =  // PosRegisterCreate | 
            //val result : PosRegister = apiInstance.posCreateRegister(posRegisterCreate)
            //result shouldBe ("TODO")
        }

        // to test posCreateTable
        should("test posCreateTable") {
            // uncomment below to test posCreateTable
            //val posTableCreate : PosTableCreate =  // PosTableCreate | 
            //val result : PosTable = apiInstance.posCreateTable(posTableCreate)
            //result shouldBe ("TODO")
        }

        // to test posDisableRegister
        should("test posDisableRegister") {
            // uncomment below to test posDisableRegister
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : PosRegister = apiInstance.posDisableRegister(id)
            //result shouldBe ("TODO")
        }

        // to test posFreeTable
        should("test posFreeTable") {
            // uncomment below to test posFreeTable
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : PosTable = apiInstance.posFreeTable(id)
            //result shouldBe ("TODO")
        }

        // to test posKasseClosing
        should("test posKasseClosing") {
            // uncomment below to test posKasseClosing
            //val body : kotlin.Any =  // kotlin.Any | 
            //val result : kotlin.Any = apiInstance.posKasseClosing(body)
            //result shouldBe ("TODO")
        }

        // to test posKasseEntries
        should("test posKasseEntries") {
            // uncomment below to test posKasseEntries
            //val result : kotlin.Any = apiInstance.posKasseEntries()
            //result shouldBe ("TODO")
        }

        // to test posKasseExport
        should("test posKasseExport") {
            // uncomment below to test posKasseExport
            //val result : kotlin.Any = apiInstance.posKasseExport()
            //result shouldBe ("TODO")
        }

        // to test posKassePayInOut
        should("test posKassePayInOut") {
            // uncomment below to test posKassePayInOut
            //val body : kotlin.Any =  // kotlin.Any | 
            //val result : kotlin.Any = apiInstance.posKassePayInOut(body)
            //result shouldBe ("TODO")
        }

        // to test posListOrders
        should("test posListOrders") {
            // uncomment below to test posListOrders
            //val status : kotlin.String = status_example // kotlin.String | Filter by order status
            //val result : kotlin.Any = apiInstance.posListOrders(status)
            //result shouldBe ("TODO")
        }

        // to test posListProducts
        should("test posListProducts") {
            // uncomment below to test posListProducts
            //val q : kotlin.String = q_example // kotlin.String | Product search
            //val result : kotlin.Any = apiInstance.posListProducts(q)
            //result shouldBe ("TODO")
        }

        // to test posListRegisters
        should("test posListRegisters") {
            // uncomment below to test posListRegisters
            //val result : kotlin.collections.List<PosRegister> = apiInstance.posListRegisters()
            //result shouldBe ("TODO")
        }

        // to test posListTables
        should("test posListTables") {
            // uncomment below to test posListTables
            //val result : kotlin.collections.List<PosTable> = apiInstance.posListTables()
            //result shouldBe ("TODO")
        }

        // to test posOrderPrint
        should("test posOrderPrint") {
            // uncomment below to test posOrderPrint
            //val orderNumber : kotlin.String = orderNumber_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.posOrderPrint(orderNumber)
            //result shouldBe ("TODO")
        }

        // to test posOrderReceipt
        should("test posOrderReceipt") {
            // uncomment below to test posOrderReceipt
            //val orderNumber : kotlin.String = orderNumber_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.posOrderReceipt(orderNumber)
            //result shouldBe ("TODO")
        }

        // to test posPayOrder
        should("test posPayOrder") {
            // uncomment below to test posPayOrder
            //val orderNumber : kotlin.String = orderNumber_example // kotlin.String | 
            //val body : kotlin.Any =  // kotlin.Any | 
            //val result : kotlin.Any = apiInstance.posPayOrder(orderNumber, body)
            //result shouldBe ("TODO")
        }

        // to test posSumupCheckout
        should("test posSumupCheckout") {
            // uncomment below to test posSumupCheckout
            //val body : kotlin.Any =  // kotlin.Any | 
            //val result : kotlin.Any = apiInstance.posSumupCheckout(body)
            //result shouldBe ("TODO")
        }

    }
}
