/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ReplenishmentApi
import org.openapitools.client.models.PluginError
import org.openapitools.client.models.ReplenishmentResponse

class ReplenishmentApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReplenishmentApi
        //val apiInstance = ReplenishmentApi()

        // to test applyReplenishments
        should("test applyReplenishments") {
            // uncomment below to test applyReplenishments
            //val targetWarehouseId : kotlin.String = targetWarehouseId_example // kotlin.String | Warehouse to be replenished. Defaults to the tenant's default warehouse.
            //val sourceWarehouseId : kotlin.String = sourceWarehouseId_example // kotlin.String | Restrict source warehouses to this id.
            //val result : kotlin.Any = apiInstance.applyReplenishments(targetWarehouseId, sourceWarehouseId)
            //result shouldBe ("TODO")
        }

        // to test getReplenishments
        should("test getReplenishments") {
            // uncomment below to test getReplenishments
            //val targetWarehouseId : kotlin.String = targetWarehouseId_example // kotlin.String | Warehouse to be replenished. Defaults to the tenant's default warehouse.
            //val sourceWarehouseId : kotlin.String = sourceWarehouseId_example // kotlin.String | Restrict source warehouses to this id.
            //val result : ReplenishmentResponse = apiInstance.getReplenishments(targetWarehouseId, sourceWarehouseId)
            //result shouldBe ("TODO")
        }

    }
}
