/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ReportsApi
import org.openapitools.client.models.BilanzReport
import org.openapitools.client.models.GuVReport
import org.openapitools.client.models.KontoReport
import org.openapitools.client.models.UmsatzsteuerReport

class ReportsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReportsApi
        //val apiInstance = ReportsApi()

        // to test bilanzReportApi
        should("test bilanzReportApi") {
            // uncomment below to test bilanzReportApi
            //val year : kotlin.Int = 56 // kotlin.Int | 
            //val month : kotlin.Int = 56 // kotlin.Int | 
            //val dateFrom : kotlin.String = dateFrom_example // kotlin.String | 
            //val dateTo : kotlin.String = dateTo_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val result : BilanzReport = apiInstance.bilanzReportApi(year, month, dateFrom, dateTo, page, pageSize)
            //result shouldBe ("TODO")
        }

        // to test guvReportApi
        should("test guvReportApi") {
            // uncomment below to test guvReportApi
            //val year : kotlin.Int = 56 // kotlin.Int | 
            //val month : kotlin.Int = 56 // kotlin.Int | 
            //val dateFrom : kotlin.String = dateFrom_example // kotlin.String | 
            //val dateTo : kotlin.String = dateTo_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val result : GuVReport = apiInstance.guvReportApi(year, month, dateFrom, dateTo, page, pageSize)
            //result shouldBe ("TODO")
        }

        // to test kontenansichtReportApi
        should("test kontenansichtReportApi") {
            // uncomment below to test kontenansichtReportApi
            //val year : kotlin.Int = 56 // kotlin.Int | 
            //val month : kotlin.Int = 56 // kotlin.Int | 
            //val dateFrom : kotlin.String = dateFrom_example // kotlin.String | 
            //val dateTo : kotlin.String = dateTo_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val result : KontoReport = apiInstance.kontenansichtReportApi(year, month, dateFrom, dateTo, page, pageSize)
            //result shouldBe ("TODO")
        }

        // to test umsatzsteuerReportApi
        should("test umsatzsteuerReportApi") {
            // uncomment below to test umsatzsteuerReportApi
            //val year : kotlin.Int = 56 // kotlin.Int | 
            //val month : kotlin.Int = 56 // kotlin.Int | 
            //val dateFrom : kotlin.String = dateFrom_example // kotlin.String | 
            //val dateTo : kotlin.String = dateTo_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val result : UmsatzsteuerReport = apiInstance.umsatzsteuerReportApi(year, month, dateFrom, dateTo, page, pageSize)
            //result shouldBe ("TODO")
        }

    }
}
