/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.RfqApi
import org.openapitools.client.models.PluginError
import org.openapitools.client.models.Rfq
import org.openapitools.client.models.RfqStatusUpdate

class RfqApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RfqApi
        //val apiInstance = RfqApi()

        // to test convertRfq
        should("test convertRfq") {
            // uncomment below to test convertRfq
            //val rfqId : kotlin.String = rfqId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.convertRfq(rfqId)
            //result shouldBe ("TODO")
        }

        // to test createRfq
        should("test createRfq") {
            // uncomment below to test createRfq
            //val rfq : Rfq =  // Rfq | 
            //val result : Rfq = apiInstance.createRfq(rfq)
            //result shouldBe ("TODO")
        }

        // to test deleteRfq
        should("test deleteRfq") {
            // uncomment below to test deleteRfq
            //val rfqId : kotlin.String = rfqId_example // kotlin.String | 
            //apiInstance.deleteRfq(rfqId)
        }

        // to test getRfq
        should("test getRfq") {
            // uncomment below to test getRfq
            //val rfqId : kotlin.String = rfqId_example // kotlin.String | 
            //val result : Rfq = apiInstance.getRfq(rfqId)
            //result shouldBe ("TODO")
        }

        // to test listRfqs
        should("test listRfqs") {
            // uncomment below to test listRfqs
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val status : kotlin.String = status_example // kotlin.String | 
            //val supplierName : kotlin.String = supplierName_example // kotlin.String | 
            //val result : kotlin.collections.List<Rfq> = apiInstance.listRfqs(page, pageSize, status, supplierName)
            //result shouldBe ("TODO")
        }

        // to test updateRfq
        should("test updateRfq") {
            // uncomment below to test updateRfq
            //val rfqId : kotlin.String = rfqId_example // kotlin.String | 
            //val body : kotlin.Any =  // kotlin.Any | 
            //val result : Rfq = apiInstance.updateRfq(rfqId, body)
            //result shouldBe ("TODO")
        }

        // to test updateRfqStatus
        should("test updateRfqStatus") {
            // uncomment below to test updateRfqStatus
            //val rfqId : kotlin.String = rfqId_example // kotlin.String | 
            //val rfqStatusUpdate : RfqStatusUpdate =  // RfqStatusUpdate | 
            //val result : Rfq = apiInstance.updateRfqStatus(rfqId, rfqStatusUpdate)
            //result shouldBe ("TODO")
        }

    }
}
