/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ShareholderApi
import org.openapitools.client.models.PluginError
import org.openapitools.client.models.Shareholder
import org.openapitools.client.models.ShareholderCreate
import org.openapitools.client.models.ShareholderUpdate

class ShareholderApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShareholderApi
        //val apiInstance = ShareholderApi()

        // to test createShareholder
        should("test createShareholder") {
            // uncomment below to test createShareholder
            //val shareholderCreate : ShareholderCreate =  // ShareholderCreate | 
            //val result : Shareholder = apiInstance.createShareholder(shareholderCreate)
            //result shouldBe ("TODO")
        }

        // to test deleteShareholder
        should("test deleteShareholder") {
            // uncomment below to test deleteShareholder
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.deleteShareholder(id)
        }

        // to test getShareholder
        should("test getShareholder") {
            // uncomment below to test getShareholder
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : Shareholder = apiInstance.getShareholder(id)
            //result shouldBe ("TODO")
        }

        // to test getShareholders
        should("test getShareholders") {
            // uncomment below to test getShareholders
            //val page : kotlin.Int = 1 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val search : kotlin.String = search_example // kotlin.String | 
            //val includeDeleted : kotlin.Boolean = true // kotlin.Boolean | Soft-delete entities: set true to include rows with `deleted_at` set.
            //val result : kotlin.collections.List<Shareholder> = apiInstance.getShareholders(page, pageSize, search, includeDeleted)
            //result shouldBe ("TODO")
        }

        // to test updateShareholder
        should("test updateShareholder") {
            // uncomment below to test updateShareholder
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val shareholderUpdate : ShareholderUpdate =  // ShareholderUpdate | 
            //val result : Shareholder = apiInstance.updateShareholder(id, shareholderUpdate)
            //result shouldBe ("TODO")
        }

    }
}
