/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.SilentPartnerApi
import org.openapitools.client.models.PluginError
import org.openapitools.client.models.SilentPartner
import org.openapitools.client.models.SilentPartnerCreate
import org.openapitools.client.models.SilentPartnerUpdate

class SilentPartnerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SilentPartnerApi
        //val apiInstance = SilentPartnerApi()

        // to test createSilentPartner
        should("test createSilentPartner") {
            // uncomment below to test createSilentPartner
            //val silentPartnerCreate : SilentPartnerCreate =  // SilentPartnerCreate | 
            //val result : SilentPartner = apiInstance.createSilentPartner(silentPartnerCreate)
            //result shouldBe ("TODO")
        }

        // to test deleteSilentPartner
        should("test deleteSilentPartner") {
            // uncomment below to test deleteSilentPartner
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.deleteSilentPartner(id)
        }

        // to test getSilentPartner
        should("test getSilentPartner") {
            // uncomment below to test getSilentPartner
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : SilentPartner = apiInstance.getSilentPartner(id)
            //result shouldBe ("TODO")
        }

        // to test getSilentPartners
        should("test getSilentPartners") {
            // uncomment below to test getSilentPartners
            //val page : kotlin.Int = 1 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val search : kotlin.String = search_example // kotlin.String | 
            //val includeDeleted : kotlin.Boolean = true // kotlin.Boolean | Soft-delete entities: set true to include rows with `deleted_at` set.
            //val result : kotlin.collections.List<SilentPartner> = apiInstance.getSilentPartners(page, pageSize, search, includeDeleted)
            //result shouldBe ("TODO")
        }

        // to test updateSilentPartner
        should("test updateSilentPartner") {
            // uncomment below to test updateSilentPartner
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val silentPartnerUpdate : SilentPartnerUpdate =  // SilentPartnerUpdate | 
            //val result : SilentPartner = apiInstance.updateSilentPartner(id, silentPartnerUpdate)
            //result shouldBe ("TODO")
        }

    }
}
