/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.StilleApi
import org.openapitools.client.models.StilleExportResponse
import org.openapitools.client.models.StilleReport

class StilleApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StilleApi
        //val apiInstance = StilleApi()

        // to test stilleExportApi
        should("test stilleExportApi") {
            // uncomment below to test stilleExportApi
            //val year : kotlin.Int = 56 // kotlin.Int | 
            //val result : StilleExportResponse = apiInstance.stilleExportApi(year)
            //result shouldBe ("TODO")
        }

        // to test stilleReportApi
        should("test stilleReportApi") {
            // uncomment below to test stilleReportApi
            //val year : kotlin.Int = 56 // kotlin.Int | 
            //val result : StilleReport = apiInstance.stilleReportApi(year)
            //result shouldBe ("TODO")
        }

    }
}
