/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.AnlageSKfzHinweis

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param gewinnVerlust 
 * @param jahr 
 * @param kfzHinweise 
 */


data class AnlageSErgebnis (

    @Json(name = "gewinn_verlust")
    val gewinnVerlust: kotlin.String,

    @Json(name = "jahr")
    val jahr: kotlin.Int,

    @Json(name = "kfz_hinweise")
    val kfzHinweise: kotlin.collections.List<AnlageSKfzHinweis>

) {


}

