/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param attachmentId Parent attachment whose history this row records.
 * @param fileName Storage key of this version's bytes.
 * @param versionNumber 1-based; ascending per attachment in upload order.
 * @param fileSize 
 * @param mimeType 
 * @param originalName 
 * @param sha256Hash 
 * @param uploadedBy 
 */


data class AttachmentVersion (

    /* Parent attachment whose history this row records. */
    @Json(name = "attachmentId")
    val attachmentId: java.util.UUID,

    /* Storage key of this version's bytes. */
    @Json(name = "fileName")
    val fileName: kotlin.String,

    /* 1-based; ascending per attachment in upload order. */
    @Json(name = "versionNumber")
    val versionNumber: kotlin.Int,

    @Json(name = "fileSize")
    val fileSize: kotlin.Long? = null,

    @Json(name = "mimeType")
    val mimeType: kotlin.String? = null,

    @Json(name = "originalName")
    val originalName: kotlin.String? = null,

    @Json(name = "sha256Hash")
    val sha256Hash: kotlin.String? = null,

    @Json(name = "uploadedBy")
    val uploadedBy: java.util.UUID? = null

) {


}

