/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param automationKey 
 * @param config 
 * @param description 
 * @param enabled 
 * @param kind 
 * @param scheduleKind 
 * @param defaultDay 
 * @param lastRunAt 
 * @param nextRunAt 
 */


data class AutomationDto (

    @Json(name = "automationKey")
    val automationKey: kotlin.String,

    @Json(name = "config")
    val config: kotlin.Any?,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "kind")
    val kind: kotlin.String,

    @Json(name = "scheduleKind")
    val scheduleKind: kotlin.String,

    @Json(name = "defaultDay")
    val defaultDay: kotlin.Int? = null,

    @Json(name = "lastRunAt")
    val lastRunAt: java.time.OffsetDateTime? = null,

    @Json(name = "nextRunAt")
    val nextRunAt: java.time.OffsetDateTime? = null

) {


}

