/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.BalanceItem

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param assets 
 * @param balanced 
 * @param equityLiabilities 
 * @param totalAssets 
 * @param totalEquityLiabilities 
 */


data class BalanceSheet (

    @Json(name = "assets")
    val assets: kotlin.collections.List<BalanceItem>,

    @Json(name = "balanced")
    val balanced: kotlin.Boolean,

    @Json(name = "equity_liabilities")
    val equityLiabilities: kotlin.collections.List<BalanceItem>,

    @Json(name = "total_assets")
    val totalAssets: kotlin.String,

    @Json(name = "total_equity_liabilities")
    val totalEquityLiabilities: kotlin.String

) {


}

