/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param code 
 * @param discountType 
 * @param discountValue 
 * @param discountedAmount 
 * @param valid 
 * @param maxDiscountAmount 
 * @param reason 
 */


data class CouponValidation (

    @Json(name = "code")
    val code: kotlin.String,

    @Json(name = "discount_type")
    val discountType: kotlin.String,

    @Json(name = "discount_value")
    val discountValue: kotlin.String,

    @Json(name = "discounted_amount")
    val discountedAmount: kotlin.String,

    @Json(name = "valid")
    val valid: kotlin.Boolean,

    @Json(name = "max_discount_amount")
    val maxDiscountAmount: kotlin.String? = null,

    @Json(name = "reason")
    val reason: kotlin.String? = null

) {


}

