/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param availableStock 
 * @param deliverableQuantity 
 * @param productId 
 * @param reservedStock 
 * @param maxSellable 
 * @param warehouseId 
 */


data class DeliverableResponse (

    @Json(name = "availableStock")
    val availableStock: kotlin.Long,

    @Json(name = "deliverableQuantity")
    val deliverableQuantity: kotlin.Long,

    @Json(name = "productId")
    val productId: java.util.UUID,

    @Json(name = "reservedStock")
    val reservedStock: kotlin.Long,

    @Json(name = "maxSellable")
    val maxSellable: kotlin.Long? = null,

    @Json(name = "warehouseId")
    val warehouseId: kotlin.String? = null

) {


}

