/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.AccountOverview
import org.openapitools.client.models.BalanceSheet
import org.openapitools.client.models.IncomeStatement
import org.openapitools.client.models.VatSummary

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accountOverview 
 * @param balanceSheet 
 * @param generatedAt 
 * @param incomeStatement 
 * @param period 
 * @param vatSummary 
 */


data class EBilanzReport (

    @Json(name = "account_overview")
    val accountOverview: kotlin.collections.List<AccountOverview>,

    @Json(name = "balance_sheet")
    val balanceSheet: BalanceSheet,

    @Json(name = "generated_at")
    val generatedAt: kotlin.String,

    @Json(name = "income_statement")
    val incomeStatement: IncomeStatement,

    @Json(name = "period")
    val period: kotlin.String,

    @Json(name = "vat_summary")
    val vatSummary: VatSummary

) {


}

