/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.EmissionTargetScope

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param baseValue 
 * @param baseYear tCO2e in the base year (actuals).
 * @param description Transition-plan narrative (ESRS E1-1 light), may be empty.
 * @param scope \"total\" | \"1\" | \"2\" | \"3\".
 * @param targetValue 
 * @param targetYear tCO2e target for the target year.
 * @param updatedAt 
 */


data class EmissionTarget (

    @Json(name = "baseValue")
    val baseValue: kotlin.String,

    /* tCO2e in the base year (actuals). */
    @Json(name = "baseYear")
    val baseYear: kotlin.Int,

    /* Transition-plan narrative (ESRS E1-1 light), may be empty. */
    @Json(name = "description")
    val description: kotlin.String,

    /* \"total\" | \"1\" | \"2\" | \"3\". */
    @Json(name = "scope")
    val scope: EmissionTargetScope,

    @Json(name = "targetValue")
    val targetValue: kotlin.String,

    /* tCO2e target for the target year. */
    @Json(name = "targetYear")
    val targetYear: kotlin.Int,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

