/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdAt 
 * @param id 
 * @param isRead 
 * @param tenantId 
 * @param title 
 * @param message 
 */


data class GdprNotification (

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "isRead")
    val isRead: kotlin.Boolean,

    @Json(name = "tenantId")
    val tenantId: java.util.UUID,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "message")
    val message: kotlin.String? = null

) {


}

