/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param freibetrag 
 * @param gesamtbelastung 
 * @param gewerbeertrag 
 * @param hebesatz 
 * @param jahr 
 * @param koerperschaftsteuer 
 * @param land 
 * @param messbetrag 
 * @param steuer 
 * @param steuerArt 
 */


data class GewerbesteuerErgebnis (

    @Json(name = "freibetrag")
    val freibetrag: kotlin.String,

    @Json(name = "gesamtbelastung")
    val gesamtbelastung: kotlin.String,

    @Json(name = "gewerbeertrag")
    val gewerbeertrag: kotlin.String,

    @Json(name = "hebesatz")
    val hebesatz: kotlin.String,

    @Json(name = "jahr")
    val jahr: kotlin.Int,

    @Json(name = "koerperschaftsteuer")
    val koerperschaftsteuer: kotlin.String,

    @Json(name = "land")
    val land: kotlin.String,

    @Json(name = "messbetrag")
    val messbetrag: kotlin.String,

    @Json(name = "steuer")
    val steuer: kotlin.String,

    @Json(name = "steuer_art")
    val steuerArt: kotlin.String

) {


}

