/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param grNumber 
 * @param lineItems JSON array of `{product_id, name, quantity, batch_number?, expiry_date?, bin_location?}`.
 * @param receiptDate 
 * @param warehouseId References the warehouse entity.
 * @param notes 
 * @param purchaseOrderId References the purchase order entity.
 * @param supplierContactId References the supplier entity.
 * @param supplierName 
 */


data class GoodsReceipt (

    @Json(name = "grNumber")
    val grNumber: kotlin.String,

    /* JSON array of `{product_id, name, quantity, batch_number?, expiry_date?, bin_location?}`. */
    @Json(name = "lineItems")
    val lineItems: kotlin.Any?,

    @Json(name = "receiptDate")
    val receiptDate: java.time.LocalDate,

    /* References the warehouse entity. */
    @Json(name = "warehouseId")
    val warehouseId: kotlin.String,

    @Json(name = "notes")
    val notes: kotlin.String? = null,

    /* References the purchase order entity. */
    @Json(name = "purchaseOrderId")
    val purchaseOrderId: kotlin.String? = null,

    /* References the supplier entity. */
    @Json(name = "supplierContactId")
    val supplierContactId: kotlin.String? = null,

    @Json(name = "supplierName")
    val supplierName: kotlin.String? = null

) {


}

