/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Partial update of the institute profile.
 *
 * @param instituteType 
 * @param kapitalmarktorientiert 
 */


data class InstituteProfileUpdate (

    @Json(name = "instituteType")
    val instituteType: kotlin.String? = null,

    @Json(name = "kapitalmarktorientiert")
    val kapitalmarktorientiert: kotlin.Boolean? = null

) {


}

