/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.EmploymentType
import org.openapitools.client.models.JobPostingStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param currency 
 * @param department 
 * @param description What the job is; markdown/HTML.
 * @param employmentType full_time | part_time | contract | internship | temporary
 * @param location 
 * @param remote 
 * @param requiredSkills List of required skill names (JSON array of strings).
 * @param requirements Structured profile of the required candidate (skills, experience).
 * @param salaryMax 
 * @param salaryMin 
 * @param status draft | published | closed
 * @param title 
 */


data class JobPostingUpdate (

    @Json(name = "currency")
    val currency: kotlin.String? = null,

    @Json(name = "department")
    val department: kotlin.String? = null,

    /* What the job is; markdown/HTML. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* full_time | part_time | contract | internship | temporary */
    @Json(name = "employmentType")
    val employmentType: EmploymentType? = null,

    @Json(name = "location")
    val location: kotlin.String? = null,

    @Json(name = "remote")
    val remote: kotlin.Boolean? = null,

    /* List of required skill names (JSON array of strings). */
    @Json(name = "requiredSkills")
    val requiredSkills: kotlin.Any? = null,

    /* Structured profile of the required candidate (skills, experience). */
    @Json(name = "requirements")
    val requirements: kotlin.String? = null,

    @Json(name = "salaryMax")
    val salaryMax: kotlin.Int? = null,

    @Json(name = "salaryMin")
    val salaryMin: kotlin.Int? = null,

    /* draft | published | closed */
    @Json(name = "status")
    val status: JobPostingStatus? = null,

    @Json(name = "title")
    val title: kotlin.String? = null

) {


}

