/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param beschreibung 
 * @param betrag 
 * @param datum 
 * @param typ 
 */


data class KostenEintrag (

    @Json(name = "beschreibung")
    val beschreibung: kotlin.String,

    @Json(name = "betrag")
    val betrag: kotlin.String,

    @Json(name = "datum")
    val datum: kotlin.String,

    @Json(name = "typ")
    val typ: kotlin.String

) {


}

