/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param customerId Referenz auf den Kunden/Kontakt.
 * @param customerName Name des Kunden (für die Suche).
 * @param kycDate Datum der KYC-Prüfung (GwG § 8).
 * @param notes Freitext-Notizen.
 * @param retentionUntil Aufbewahrungsfrist (GwG § 8 Abs. 4: 5 Jahre).
 * @param riskAssessment Risikoeinschätzung (z. B. Risikoklasse).
 */


data class KycRecordUpdate (

    /* Referenz auf den Kunden/Kontakt. */
    @Json(name = "customerId")
    val customerId: kotlin.String? = null,

    /* Name des Kunden (für die Suche). */
    @Json(name = "customerName")
    val customerName: kotlin.String? = null,

    /* Datum der KYC-Prüfung (GwG § 8). */
    @Json(name = "kycDate")
    val kycDate: java.time.LocalDate? = null,

    /* Freitext-Notizen. */
    @Json(name = "notes")
    val notes: kotlin.String? = null,

    /* Aufbewahrungsfrist (GwG § 8 Abs. 4: 5 Jahre). */
    @Json(name = "retentionUntil")
    val retentionUntil: java.time.LocalDate? = null,

    /* Risikoeinschätzung (z. B. Risikoklasse). */
    @Json(name = "riskAssessment")
    val riskAssessment: kotlin.String? = null

) {


}

