/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: DE,EN,FR,ES,IT,NL,PL,PT,TR,RU,UK,CS,EL,HU,RO,SV,DA,FI,NO,SK,SL,HR,BG,ET,LV,LT,MT,AR,ZH,JA,KO,TH,VI,ID,HI,AB,AA,AF,AK,SQ,AM,AN,HY,AS,AV,AE,AY,AZ,BM,BA,EU,BE,BN,BI,BS,BR,MY,CA,CH,CE,NY,CU,CV,KW,CO,CR,DV,DZ,EO,EE,FO,FJ,FY,FF,GD,GL,LG,KA,KL,GN,GU,HT,HA,HE,HZ,HO,IS,IO,IG,IA,IE,IU,IK,GA,JV,KN,KR,KS,KK,KM,KI,RW,KY,KV,KG,KJ,KU,LO,LA,LI,LN,LU,LB,MK,MG,MS,ML,GV,MI,MR,MH,MN,NA,NV,ND,NR,NG,NE,NB,NN,OC,OJ,OR,OM,OS,PI,PS,FA,PA,QU,RM,RN,SE,SM,SG,SA,SC,SR,SN,SD,SI,SO,ST,SU,SW,SS,TL,TY,TG,TA,TT,TE,BO,TI,TO,TS,TN,TK,TW,UG,UR,UZ,VE,VO,WA,CY,WO,XH,II,YI,YO,ZA,ZU,BB,CB,DB,EB,FB,GB,HB,IB,JB,KB,MB,OB,PB,QB,RB,SB,TB,UB,VB,WB,XB,YB,ZB
 */

@JsonClass(generateAdapter = false)
enum class LanguageCode(val value: kotlin.String) {

    @Json(name = "DE")
    DE("DE"),

    @Json(name = "EN")
    EN("EN"),

    @Json(name = "FR")
    FR("FR"),

    @Json(name = "ES")
    ES("ES"),

    @Json(name = "IT")
    IT("IT"),

    @Json(name = "NL")
    NL("NL"),

    @Json(name = "PL")
    PL("PL"),

    @Json(name = "PT")
    PT("PT"),

    @Json(name = "TR")
    TR("TR"),

    @Json(name = "RU")
    RU("RU"),

    @Json(name = "UK")
    UK("UK"),

    @Json(name = "CS")
    CS("CS"),

    @Json(name = "EL")
    EL("EL"),

    @Json(name = "HU")
    HU("HU"),

    @Json(name = "RO")
    RO("RO"),

    @Json(name = "SV")
    SV("SV"),

    @Json(name = "DA")
    DA("DA"),

    @Json(name = "FI")
    FI("FI"),

    @Json(name = "NO")
    NO("NO"),

    @Json(name = "SK")
    SK("SK"),

    @Json(name = "SL")
    SL("SL"),

    @Json(name = "HR")
    HR("HR"),

    @Json(name = "BG")
    BG("BG"),

    @Json(name = "ET")
    ET("ET"),

    @Json(name = "LV")
    LV("LV"),

    @Json(name = "LT")
    LT("LT"),

    @Json(name = "MT")
    MT("MT"),

    @Json(name = "AR")
    AR("AR"),

    @Json(name = "ZH")
    ZH("ZH"),

    @Json(name = "JA")
    JA("JA"),

    @Json(name = "KO")
    KO("KO"),

    @Json(name = "TH")
    TH("TH"),

    @Json(name = "VI")
    VI("VI"),

    @Json(name = "ID")
    ID("ID"),

    @Json(name = "HI")
    HI("HI"),

    @Json(name = "AB")
    AB("AB"),

    @Json(name = "AA")
    AA("AA"),

    @Json(name = "AF")
    AF("AF"),

    @Json(name = "AK")
    AK("AK"),

    @Json(name = "SQ")
    SQ("SQ"),

    @Json(name = "AM")
    AM("AM"),

    @Json(name = "AN")
    AN("AN"),

    @Json(name = "HY")
    HY("HY"),

    @Json(name = "AS")
    AS("AS"),

    @Json(name = "AV")
    AV("AV"),

    @Json(name = "AE")
    AE("AE"),

    @Json(name = "AY")
    AY("AY"),

    @Json(name = "AZ")
    AZ("AZ"),

    @Json(name = "BM")
    BM("BM"),

    @Json(name = "BA")
    BA("BA"),

    @Json(name = "EU")
    EU("EU"),

    @Json(name = "BE")
    BE("BE"),

    @Json(name = "BN")
    BN("BN"),

    @Json(name = "BI")
    BI("BI"),

    @Json(name = "BS")
    BS("BS"),

    @Json(name = "BR")
    BR("BR"),

    @Json(name = "MY")
    MY("MY"),

    @Json(name = "CA")
    CA("CA"),

    @Json(name = "CH")
    CH("CH"),

    @Json(name = "CE")
    CE("CE"),

    @Json(name = "NY")
    NY("NY"),

    @Json(name = "CU")
    CU("CU"),

    @Json(name = "CV")
    CV("CV"),

    @Json(name = "KW")
    KW("KW"),

    @Json(name = "CO")
    CO("CO"),

    @Json(name = "CR")
    CR("CR"),

    @Json(name = "DV")
    DV("DV"),

    @Json(name = "DZ")
    DZ("DZ"),

    @Json(name = "EO")
    EO("EO"),

    @Json(name = "EE")
    EE("EE"),

    @Json(name = "FO")
    FO("FO"),

    @Json(name = "FJ")
    FJ("FJ"),

    @Json(name = "FY")
    FY("FY"),

    @Json(name = "FF")
    FF("FF"),

    @Json(name = "GD")
    GD("GD"),

    @Json(name = "GL")
    GL("GL"),

    @Json(name = "LG")
    LG("LG"),

    @Json(name = "KA")
    KA("KA"),

    @Json(name = "KL")
    KL("KL"),

    @Json(name = "GN")
    GN("GN"),

    @Json(name = "GU")
    GU("GU"),

    @Json(name = "HT")
    HT("HT"),

    @Json(name = "HA")
    HA("HA"),

    @Json(name = "HE")
    HE("HE"),

    @Json(name = "HZ")
    HZ("HZ"),

    @Json(name = "HO")
    HO("HO"),

    @Json(name = "IS")
    IS("IS"),

    @Json(name = "IO")
    IO("IO"),

    @Json(name = "IG")
    IG("IG"),

    @Json(name = "IA")
    IA("IA"),

    @Json(name = "IE")
    IE("IE"),

    @Json(name = "IU")
    IU("IU"),

    @Json(name = "IK")
    IK("IK"),

    @Json(name = "GA")
    GA("GA"),

    @Json(name = "JV")
    JV("JV"),

    @Json(name = "KN")
    KN("KN"),

    @Json(name = "KR")
    KR("KR"),

    @Json(name = "KS")
    KS("KS"),

    @Json(name = "KK")
    KK("KK"),

    @Json(name = "KM")
    KM("KM"),

    @Json(name = "KI")
    KI("KI"),

    @Json(name = "RW")
    RW("RW"),

    @Json(name = "KY")
    KY("KY"),

    @Json(name = "KV")
    KV("KV"),

    @Json(name = "KG")
    KG("KG"),

    @Json(name = "KJ")
    KJ("KJ"),

    @Json(name = "KU")
    KU("KU"),

    @Json(name = "LO")
    LO("LO"),

    @Json(name = "LA")
    LA("LA"),

    @Json(name = "LI")
    LI("LI"),

    @Json(name = "LN")
    LN("LN"),

    @Json(name = "LU")
    LU("LU"),

    @Json(name = "LB")
    LB("LB"),

    @Json(name = "MK")
    MK("MK"),

    @Json(name = "MG")
    MG("MG"),

    @Json(name = "MS")
    MS("MS"),

    @Json(name = "ML")
    ML("ML"),

    @Json(name = "GV")
    GV("GV"),

    @Json(name = "MI")
    MI("MI"),

    @Json(name = "MR")
    MR("MR"),

    @Json(name = "MH")
    MH("MH"),

    @Json(name = "MN")
    MN("MN"),

    @Json(name = "NA")
    NA("NA"),

    @Json(name = "NV")
    NV("NV"),

    @Json(name = "ND")
    ND("ND"),

    @Json(name = "NR")
    NR("NR"),

    @Json(name = "NG")
    NG("NG"),

    @Json(name = "NE")
    NE("NE"),

    @Json(name = "NB")
    NB("NB"),

    @Json(name = "NN")
    NN("NN"),

    @Json(name = "OC")
    OC("OC"),

    @Json(name = "OJ")
    OJ("OJ"),

    @Json(name = "OR")
    OR("OR"),

    @Json(name = "OM")
    OM("OM"),

    @Json(name = "OS")
    OS("OS"),

    @Json(name = "PI")
    PI("PI"),

    @Json(name = "PS")
    PS("PS"),

    @Json(name = "FA")
    FA("FA"),

    @Json(name = "PA")
    PA("PA"),

    @Json(name = "QU")
    QU("QU"),

    @Json(name = "RM")
    RM("RM"),

    @Json(name = "RN")
    RN("RN"),

    @Json(name = "SE")
    SE("SE"),

    @Json(name = "SM")
    SM("SM"),

    @Json(name = "SG")
    SG("SG"),

    @Json(name = "SA")
    SA("SA"),

    @Json(name = "SC")
    SC("SC"),

    @Json(name = "SR")
    SR("SR"),

    @Json(name = "SN")
    SN("SN"),

    @Json(name = "SD")
    SD("SD"),

    @Json(name = "SI")
    SI("SI"),

    @Json(name = "SO")
    SO("SO"),

    @Json(name = "ST")
    ST("ST"),

    @Json(name = "SU")
    SU("SU"),

    @Json(name = "SW")
    SW("SW"),

    @Json(name = "SS")
    SS("SS"),

    @Json(name = "TL")
    TL("TL"),

    @Json(name = "TY")
    TY("TY"),

    @Json(name = "TG")
    TG("TG"),

    @Json(name = "TA")
    TA("TA"),

    @Json(name = "TT")
    TT("TT"),

    @Json(name = "TE")
    TE("TE"),

    @Json(name = "BO")
    BO("BO"),

    @Json(name = "TI")
    TI("TI"),

    @Json(name = "TO")
    TO("TO"),

    @Json(name = "TS")
    TS("TS"),

    @Json(name = "TN")
    TN("TN"),

    @Json(name = "TK")
    TK("TK"),

    @Json(name = "TW")
    TW("TW"),

    @Json(name = "UG")
    UG("UG"),

    @Json(name = "UR")
    UR("UR"),

    @Json(name = "UZ")
    UZ("UZ"),

    @Json(name = "VE")
    VE("VE"),

    @Json(name = "VO")
    VO("VO"),

    @Json(name = "WA")
    WA("WA"),

    @Json(name = "CY")
    CY("CY"),

    @Json(name = "WO")
    WO("WO"),

    @Json(name = "XH")
    XH("XH"),

    @Json(name = "II")
    II("II"),

    @Json(name = "YI")
    YI("YI"),

    @Json(name = "YO")
    YO("YO"),

    @Json(name = "ZA")
    ZA("ZA"),

    @Json(name = "ZU")
    ZU("ZU"),

    @Json(name = "BB")
    BB("BB"),

    @Json(name = "CB")
    CB("CB"),

    @Json(name = "DB")
    DB("DB"),

    @Json(name = "EB")
    EB("EB"),

    @Json(name = "FB")
    FB("FB"),

    @Json(name = "GB")
    GB("GB"),

    @Json(name = "HB")
    HB("HB"),

    @Json(name = "IB")
    IB("IB"),

    @Json(name = "JB")
    JB("JB"),

    @Json(name = "KB")
    KB("KB"),

    @Json(name = "MB")
    MB("MB"),

    @Json(name = "OB")
    OB("OB"),

    @Json(name = "PB")
    PB("PB"),

    @Json(name = "QB")
    QB("QB"),

    @Json(name = "RB")
    RB("RB"),

    @Json(name = "SB")
    SB("SB"),

    @Json(name = "TB")
    TB("TB"),

    @Json(name = "UB")
    UB("UB"),

    @Json(name = "VB")
    VB("VB"),

    @Json(name = "WB")
    WB("WB"),

    @Json(name = "XB")
    XB("XB"),

    @Json(name = "YB")
    YB("YB"),

    @Json(name = "ZB")
    ZB("ZB");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is LanguageCode) "$data" else null

        /**
         * Returns a valid [LanguageCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): LanguageCode? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

