/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Optional filter for `POST /api/v1/legal/documents/reset`; empty body restores every document of the tenant.
 *
 * @param docType 
 * @param lang 
 */


data class LegalDocumentReset (

    @Json(name = "docType")
    val docType: kotlin.String? = null,

    @Json(name = "lang")
    val lang: kotlin.String? = null

) {


}

