/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Stock movement type.
 *
 * Values: goods_receipt,goods_receipt_reversal,transfer_in,transfer_out,return_restock,production_consumption,production_completion,inventory_adjustment,sale,other
 */

@JsonClass(generateAdapter = false)
enum class MovementType(val value: kotlin.String) {

    @Json(name = "goods_receipt")
    goods_receipt("goods_receipt"),

    @Json(name = "goods_receipt_reversal")
    goods_receipt_reversal("goods_receipt_reversal"),

    @Json(name = "transfer_in")
    transfer_in("transfer_in"),

    @Json(name = "transfer_out")
    transfer_out("transfer_out"),

    @Json(name = "return_restock")
    return_restock("return_restock"),

    @Json(name = "production_consumption")
    production_consumption("production_consumption"),

    @Json(name = "production_completion")
    production_completion("production_completion"),

    @Json(name = "inventory_adjustment")
    inventory_adjustment("inventory_adjustment"),

    @Json(name = "sale")
    sale("sale"),

    @Json(name = "other")
    other("other");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MovementType) "$data" else null

        /**
         * Returns a valid [MovementType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MovementType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

