/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.ReminderLevel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param amountDue 
 * @param amountPaid 
 * @param invoiceId 
 * @param invoiceNumber 
 * @param issueDate 
 * @param openAmount 
 * @param reminderLevel 
 * @param customerId 
 * @param daysOverdue 
 * @param dueDate 
 */


data class OpenItem (

    @Json(name = "amount_due")
    val amountDue: kotlin.String,

    @Json(name = "amount_paid")
    val amountPaid: kotlin.String,

    @Json(name = "invoice_id")
    val invoiceId: kotlin.String,

    @Json(name = "invoice_number")
    val invoiceNumber: kotlin.String,

    @Json(name = "issue_date")
    val issueDate: kotlin.String,

    @Json(name = "open_amount")
    val openAmount: kotlin.String,

    @Json(name = "reminder_level")
    val reminderLevel: ReminderLevel,

    @Json(name = "customer_id")
    val customerId: kotlin.String? = null,

    @Json(name = "days_overdue")
    val daysOverdue: kotlin.Long? = null,

    @Json(name = "due_date")
    val dueDate: kotlin.String? = null

) {


}

