/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdAt 
 * @param customerId 
 * @param deliveryNotePrinted 
 * @param items 
 * @param itemsCount 
 * @param labelPrinted 
 * @param orderNumber 
 * @param orderStatus 
 * @param shippingMethod 
 * @param shipmentId 
 * @param shippingAddress 
 * @param trackingNumber 
 * @param videoRecording 
 */


data class PackingQueueItem (

    @Json(name = "created_at")
    val createdAt: kotlin.String,

    @Json(name = "customer_id")
    val customerId: kotlin.String,

    @Json(name = "delivery_note_printed")
    val deliveryNotePrinted: kotlin.Boolean,

    @Json(name = "items")
    val items: kotlin.Any?,

    @Json(name = "items_count")
    val itemsCount: kotlin.Int,

    @Json(name = "label_printed")
    val labelPrinted: kotlin.Boolean,

    @Json(name = "order_number")
    val orderNumber: kotlin.String,

    @Json(name = "order_status")
    val orderStatus: kotlin.String,

    @Json(name = "shipping_method")
    val shippingMethod: kotlin.String,

    @Json(name = "shipment_id")
    val shipmentId: kotlin.String? = null,

    @Json(name = "shipping_address")
    val shippingAddress: kotlin.Any? = null,

    @Json(name = "tracking_number")
    val trackingNumber: kotlin.String? = null,

    @Json(name = "video_recording")
    val videoRecording: kotlin.String? = null

) {


}

