/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param orderNumber 
 * @param notes 
 * @param shipmentId 
 * @param videoUrl 
 */


data class PackingCompleteRequest (

    @Json(name = "order_number")
    val orderNumber: kotlin.String,

    @Json(name = "notes")
    val notes: kotlin.String? = null,

    @Json(name = "shipment_id")
    val shipmentId: kotlin.String? = null,

    @Json(name = "video_url")
    val videoUrl: kotlin.String? = null

) {


}

