/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.PackingQueueItem

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param items 
 * @param page 
 * @param pageSize 
 * @param totalCount 
 */


data class PackingQueue (

    @Json(name = "items")
    val items: kotlin.collections.List<PackingQueueItem>,

    @Json(name = "page")
    val page: kotlin.Int,

    @Json(name = "page_size")
    val pageSize: kotlin.Int,

    @Json(name = "total_count")
    val totalCount: kotlin.Long

) {


}

