/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.GatewayType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param config 
 * @param createdAt 
 * @param deletedAt 
 * @param enabled 
 * @param gatewayType 
 * @param label 
 * @param updatedAt 
 */


data class PaymentGatewayUpdate (

    @Json(name = "config")
    val config: kotlin.Any? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "deletedAt")
    val deletedAt: java.time.OffsetDateTime? = null,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null,

    @Json(name = "gatewayType")
    val gatewayType: GatewayType? = null,

    @Json(name = "label")
    val label: kotlin.String? = null,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

