/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productId The parent product this variant belongs to. References the product entity.
 * @param sku Variant-specific SKU (must be unique per tenant).
 * @param barcode 
 * @param imageLink 
 * @param isActive 
 * @param name Human-readable variant label, e.g. \"Red / M\".
 * @param optionValues Option name → value map, e.g. `{\"Color\": \"Red\", \"Size\": \"M\"}`.
 * @param price Explicit override price for this variant (takes precedence over parent price + delta).
 * @param priceDelta Price adjustment relative to the parent product's `default_price`.
 * @param stockQuantity Variant-level stock (optional — may be tracked on the parent only).
 */


data class ProductVariantCreate (

    /* The parent product this variant belongs to. References the product entity. */
    @Json(name = "productId")
    val productId: java.util.UUID,

    /* Variant-specific SKU (must be unique per tenant). */
    @Json(name = "sku")
    val sku: kotlin.String,

    @Json(name = "barcode")
    val barcode: kotlin.String? = null,

    @Json(name = "imageLink")
    val imageLink: kotlin.String? = null,

    @Json(name = "isActive")
    val isActive: kotlin.Boolean? = null,

    /* Human-readable variant label, e.g. \"Red / M\". */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Option name → value map, e.g. `{\"Color\": \"Red\", \"Size\": \"M\"}`. */
    @Json(name = "optionValues")
    val optionValues: kotlin.Any? = null,

    /* Explicit override price for this variant (takes precedence over parent price + delta). */
    @Json(name = "price")
    val price: kotlin.String? = null,

    /* Price adjustment relative to the parent product's `default_price`. */
    @Json(name = "priceDelta")
    val priceDelta: kotlin.String? = null,

    /* Variant-level stock (optional — may be tracked on the parent only). */
    @Json(name = "stockQuantity")
    val stockQuantity: kotlin.Long? = null

) {


}

