/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param description 
 * @param name 
 * @param parentCategoryId References the category entity.
 * @param sortOrder 
 */


data class ProductCategoryUpdate (

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    /* References the category entity. */
    @Json(name = "parentCategoryId")
    val parentCategoryId: kotlin.String? = null,

    @Json(name = "sortOrder")
    val sortOrder: kotlin.Int? = null

) {


}

