/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param options 
 * @param optionsEn 
 * @param question 
 * @param questionEn 
 */


data class QuizQuestion (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "options")
    val options: kotlin.collections.List<kotlin.String>,

    @Json(name = "optionsEn")
    val optionsEn: kotlin.collections.List<kotlin.String>,

    @Json(name = "question")
    val question: kotlin.String,

    @Json(name = "questionEn")
    val questionEn: kotlin.String

) {


}

