/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.PrecedingSalesVoucherType
import org.openapitools.client.models.VoucherStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param currency 
 * @param voucherDate 
 * @param voucherStatus 
 * @param address 
 * @param contactId References the contact entity.
 * @param contactName 
 * @param expirationDate 
 * @param files 
 * @param introduction 
 * @param lineItems 
 * @param precedingSalesVoucherId References the preceding sales voucher entity.
 * @param precedingSalesVoucherType 
 * @param quotationNumber 
 * @param remark 
 * @param subtotal 
 * @param taxCondition 
 * @param title 
 * @param totalAmount 
 * @param totalTax 
 */


data class Quotation (

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "voucherDate")
    val voucherDate: java.time.LocalDate,

    @Json(name = "voucherStatus")
    val voucherStatus: VoucherStatus,

    @Json(name = "address")
    val address: kotlin.Any? = null,

    /* References the contact entity. */
    @Json(name = "contactId")
    val contactId: kotlin.String? = null,

    @Json(name = "contactName")
    val contactName: kotlin.String? = null,

    @Json(name = "expirationDate")
    val expirationDate: java.time.LocalDate? = null,

    @Json(name = "files")
    val files: kotlin.Any? = null,

    @Json(name = "introduction")
    val introduction: kotlin.String? = null,

    @Json(name = "lineItems")
    val lineItems: kotlin.Any? = null,

    /* References the preceding sales voucher entity. */
    @Json(name = "precedingSalesVoucherId")
    val precedingSalesVoucherId: kotlin.String? = null,

    @Json(name = "precedingSalesVoucherType")
    val precedingSalesVoucherType: PrecedingSalesVoucherType? = null,

    @Json(name = "quotationNumber")
    val quotationNumber: kotlin.String? = null,

    @Json(name = "remark")
    val remark: kotlin.String? = null,

    @Json(name = "subtotal")
    val subtotal: kotlin.String? = null,

    @Json(name = "taxCondition")
    val taxCondition: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "totalAmount")
    val totalAmount: kotlin.String? = null,

    @Json(name = "totalTax")
    val totalTax: kotlin.String? = null

) {


}

