/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.MeteredUsage
import org.openapitools.client.models.PlanFeatures
import org.openapitools.client.models.PlanLimits
import org.openapitools.client.models.UsageSnapshot

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param features 
 * @param isTrialing 
 * @param limits 
 * @param metered 
 * @param plan 
 * @param planName 
 * @param usage 
 * @param trialEndsAt 
 */


data class QuotaOverview (

    @Json(name = "features")
    val features: PlanFeatures,

    @Json(name = "isTrialing")
    val isTrialing: kotlin.Boolean,

    @Json(name = "limits")
    val limits: PlanLimits,

    @Json(name = "metered")
    val metered: kotlin.collections.List<MeteredUsage>,

    @Json(name = "plan")
    val plan: kotlin.String,

    @Json(name = "planName")
    val planName: kotlin.String,

    @Json(name = "usage")
    val usage: UsageSnapshot,

    @Json(name = "trialEndsAt")
    val trialEndsAt: java.time.OffsetDateTime? = null

) {


}

