/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Stock movement reference type.
 *
 * Values: goods_receipt,production_order,transfer_in,stock_transfer,return_order,inventory_count
 */

@JsonClass(generateAdapter = false)
enum class ReferenceType(val value: kotlin.String) {

    @Json(name = "goods_receipt")
    goods_receipt("goods_receipt"),

    @Json(name = "production_order")
    production_order("production_order"),

    @Json(name = "transfer_in")
    transfer_in("transfer_in"),

    @Json(name = "stock_transfer")
    stock_transfer("stock_transfer"),

    @Json(name = "return_order")
    return_order("return_order"),

    @Json(name = "inventory_count")
    inventory_count("inventory_count");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ReferenceType) "$data" else null

        /**
         * Returns a valid [ReferenceType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ReferenceType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

