/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.ReturnOrderStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param returnNumber 
 * @param status One of: requested | received | inspected | restocked | closed
 * @param customerContactId References the contact entity.
 * @param customerName 
 * @param lineItems JSON array of `{product_id, name, quantity, condition, restock, batch_number?}`.
 * @param notes 
 * @param orderId References the order entity.
 * @param orderNumber 
 * @param returnReason 
 * @param warehouseId Warehouse into which restockable items are returned. References the warehouse entity.
 */


data class ReturnOrder (

    @Json(name = "returnNumber")
    val returnNumber: kotlin.String,

    /* One of: requested | received | inspected | restocked | closed */
    @Json(name = "status")
    val status: ReturnOrderStatus,

    /* References the contact entity. */
    @Json(name = "customerContactId")
    val customerContactId: kotlin.String? = null,

    @Json(name = "customerName")
    val customerName: kotlin.String? = null,

    /* JSON array of `{product_id, name, quantity, condition, restock, batch_number?}`. */
    @Json(name = "lineItems")
    val lineItems: kotlin.Any? = null,

    @Json(name = "notes")
    val notes: kotlin.String? = null,

    /* References the order entity. */
    @Json(name = "orderId")
    val orderId: kotlin.String? = null,

    @Json(name = "orderNumber")
    val orderNumber: kotlin.String? = null,

    @Json(name = "returnReason")
    val returnReason: kotlin.String? = null,

    /* Warehouse into which restockable items are returned. References the warehouse entity. */
    @Json(name = "warehouseId")
    val warehouseId: kotlin.String? = null

) {


}

