/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.RfqStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param lineItems JSON array of `{product_id, name, sku, quantity, requested_unit_price?, quoted_unit_price?}`.
 * @param requestedDate 
 * @param rfqNumber 
 * @param status One of: draft | sent | offer_received | rejected | converted
 * @param currency 
 * @param notes 
 * @param responseDate 
 * @param supplierContactId References the supplier entity.
 * @param supplierName 
 */


data class RfqCreate (

    /* JSON array of `{product_id, name, sku, quantity, requested_unit_price?, quoted_unit_price?}`. */
    @Json(name = "lineItems")
    val lineItems: kotlin.Any?,

    @Json(name = "requestedDate")
    val requestedDate: java.time.LocalDate,

    @Json(name = "rfqNumber")
    val rfqNumber: kotlin.String,

    /* One of: draft | sent | offer_received | rejected | converted */
    @Json(name = "status")
    val status: RfqStatus,

    @Json(name = "currency")
    val currency: kotlin.String? = null,

    @Json(name = "notes")
    val notes: kotlin.String? = null,

    @Json(name = "responseDate")
    val responseDate: java.time.LocalDate? = null,

    /* References the supplier entity. */
    @Json(name = "supplierContactId")
    val supplierContactId: kotlin.String? = null,

    @Json(name = "supplierName")
    val supplierName: kotlin.String? = null

) {


}

