/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * RFQ status.
 *
 * Values: draft,sent,offer_received,rejected,converted
 */

@JsonClass(generateAdapter = false)
enum class RfqStatus(val value: kotlin.String) {

    @Json(name = "draft")
    draft("draft"),

    @Json(name = "sent")
    sent("sent"),

    @Json(name = "offer_received")
    offer_received("offer_received"),

    @Json(name = "rejected")
    rejected("rejected"),

    @Json(name = "converted")
    converted("converted");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is RfqStatus) "$data" else null

        /**
         * Returns a valid [RfqStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): RfqStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

