/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param completionId 
 * @param passScore 
 * @param passed 
 * @param score 
 * @param certificateId 
 * @param validUntil 
 */


data class SubmitResultResponse (

    @Json(name = "completionId")
    val completionId: java.util.UUID,

    @Json(name = "passScore")
    val passScore: kotlin.Int,

    @Json(name = "passed")
    val passed: kotlin.Boolean,

    @Json(name = "score")
    val score: kotlin.Int,

    @Json(name = "certificateId")
    val certificateId: kotlin.String? = null,

    @Json(name = "validUntil")
    val validUntil: java.time.OffsetDateTime? = null

) {


}

