/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param answers Selected answer indices (required for scored builtin trainings).
 * @param score Score 0–100. Only trusted for plugin trainings without server-side scoring; builtin trainings are always re-scored from `answers`.
 * @param trainingCode 
 * @param assignmentId 
 */


data class SubmitResultDto (

    /* Selected answer indices (required for scored builtin trainings). */
    @Json(name = "answers")
    val answers: kotlin.collections.List<kotlin.Int>,

    /* Score 0–100. Only trusted for plugin trainings without server-side scoring; builtin trainings are always re-scored from `answers`. */
    @Json(name = "score")
    val score: kotlin.Int,

    @Json(name = "trainingCode")
    val trainingCode: kotlin.String,

    @Json(name = "assignmentId")
    val assignmentId: java.util.UUID? = null

) {


}

