/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.Address
import org.openapitools.client.models.CartItemInput

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param items 
 * @param recipient 
 * @param sender 
 * @param customerAnnualVolume 
 */


data class SuitabilityRequest (

    @Json(name = "items")
    val items: kotlin.collections.List<CartItemInput>,

    @Json(name = "recipient")
    val recipient: Address,

    @Json(name = "sender")
    val sender: Address,

    @Json(name = "customer_annual_volume")
    val customerAnnualVolume: kotlin.Int? = null

) {


}

