/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.SupplierInvoiceStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param invoiceDate 
 * @param invoiceNumber 
 * @param lineItems JSON array of `{product_id, name, quantity, unitPriceNet, taxRate}`.
 * @param status One of: draft | matched | has_variances | posted | cancelled
 * @param currency 
 * @param goodsReceiptId References the goods receipt entity.
 * @param notes 
 * @param purchaseOrderId References the purchase order entity.
 * @param supplierContactId References the supplier entity.
 * @param supplierName 
 * @param totalGrossAmount 
 * @param totalNetAmount 
 */


data class SupplierInvoice (

    @Json(name = "invoiceDate")
    val invoiceDate: java.time.LocalDate,

    @Json(name = "invoiceNumber")
    val invoiceNumber: kotlin.String,

    /* JSON array of `{product_id, name, quantity, unitPriceNet, taxRate}`. */
    @Json(name = "lineItems")
    val lineItems: kotlin.Any?,

    /* One of: draft | matched | has_variances | posted | cancelled */
    @Json(name = "status")
    val status: SupplierInvoiceStatus,

    @Json(name = "currency")
    val currency: kotlin.String? = null,

    /* References the goods receipt entity. */
    @Json(name = "goodsReceiptId")
    val goodsReceiptId: kotlin.String? = null,

    @Json(name = "notes")
    val notes: kotlin.String? = null,

    /* References the purchase order entity. */
    @Json(name = "purchaseOrderId")
    val purchaseOrderId: kotlin.String? = null,

    /* References the supplier entity. */
    @Json(name = "supplierContactId")
    val supplierContactId: kotlin.String? = null,

    @Json(name = "supplierName")
    val supplierName: kotlin.String? = null,

    @Json(name = "totalGrossAmount")
    val totalGrossAmount: kotlin.String? = null,

    @Json(name = "totalNetAmount")
    val totalNetAmount: kotlin.String? = null

) {


}

