/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.SupportChannelType
import org.openapitools.client.models.SupportTicketStatus
import org.openapitools.client.models.TicketPriority

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param assignedTo 
 * @param channelId 
 * @param channelType 
 * @param closedAt 
 * @param createdAt 
 * @param customerEmail 
 * @param customerId References the customer entity.
 * @param customerName 
 * @param externalId 
 * @param firstMessageAt 
 * @param lastMessageAt 
 * @param leadId References the lead entity.
 * @param messageCount 
 * @param orderRef 
 * @param priority 
 * @param resolution 
 * @param status 
 * @param subject 
 * @param tags 
 * @param tenantId 
 * @param updatedAt 
 */


data class SupportTicketUpdate (

    @Json(name = "assignedTo")
    val assignedTo: java.util.UUID? = null,

    @Json(name = "channelId")
    val channelId: java.util.UUID? = null,

    @Json(name = "channelType")
    val channelType: SupportChannelType? = null,

    @Json(name = "closedAt")
    val closedAt: java.time.OffsetDateTime? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "customerEmail")
    val customerEmail: kotlin.String? = null,

    /* References the customer entity. */
    @Json(name = "customerId")
    val customerId: kotlin.String? = null,

    @Json(name = "customerName")
    val customerName: kotlin.String? = null,

    @Json(name = "externalId")
    val externalId: kotlin.String? = null,

    @Json(name = "firstMessageAt")
    val firstMessageAt: java.time.OffsetDateTime? = null,

    @Json(name = "lastMessageAt")
    val lastMessageAt: java.time.OffsetDateTime? = null,

    /* References the lead entity. */
    @Json(name = "leadId")
    val leadId: java.util.UUID? = null,

    @Json(name = "messageCount")
    val messageCount: kotlin.Int? = null,

    @Json(name = "orderRef")
    val orderRef: kotlin.String? = null,

    @Json(name = "priority")
    val priority: TicketPriority? = null,

    @Json(name = "resolution")
    val resolution: kotlin.String? = null,

    @Json(name = "status")
    val status: SupportTicketStatus? = null,

    @Json(name = "subject")
    val subject: kotlin.String? = null,

    @Json(name = "tags")
    val tags: kotlin.Any? = null,

    @Json(name = "tenantId")
    val tenantId: java.util.UUID? = null,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

