/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param currency Currency for the minimum order value.
 * @param supplierContactId The supplier this condition applies to (`contact_id`). References the supplier entity.
 * @param deliveryTerms Incoterms, e.g. \"EXW\", \"DAP\".
 * @param earlyPaymentDiscountPercent Early-payment discount percentage (Skonto), e.g. 2.0.
 * @param isDefault Is this the default condition for the supplier?
 * @param minimumOrderValue Minimum order value required for this supplier.
 * @param notes 
 * @param paymentDueDays Number of days within which payment is due.
 * @param paymentTerms Payment terms, e.g. \"14 Tage, 2% Skonto\".
 * @param supplierName The name of the supplier, denormalized for easy listing.
 * @param volumeDiscountTiers Tiered discounts: JSON array of `{min_quantity, discount_percent}`.
 */


data class SupplierCondition (

    /* Currency for the minimum order value. */
    @Json(name = "currency")
    val currency: kotlin.String,

    /* The supplier this condition applies to (`contact_id`). References the supplier entity. */
    @Json(name = "supplierContactId")
    val supplierContactId: kotlin.String,

    /* Incoterms, e.g. \"EXW\", \"DAP\". */
    @Json(name = "deliveryTerms")
    val deliveryTerms: kotlin.String? = null,

    /* Early-payment discount percentage (Skonto), e.g. 2.0. */
    @Json(name = "earlyPaymentDiscountPercent")
    val earlyPaymentDiscountPercent: kotlin.String? = null,

    /* Is this the default condition for the supplier? */
    @Json(name = "isDefault")
    val isDefault: kotlin.Boolean? = null,

    /* Minimum order value required for this supplier. */
    @Json(name = "minimumOrderValue")
    val minimumOrderValue: kotlin.String? = null,

    @Json(name = "notes")
    val notes: kotlin.String? = null,

    /* Number of days within which payment is due. */
    @Json(name = "paymentDueDays")
    val paymentDueDays: kotlin.Int? = null,

    /* Payment terms, e.g. \"14 Tage, 2% Skonto\". */
    @Json(name = "paymentTerms")
    val paymentTerms: kotlin.String? = null,

    /* The name of the supplier, denormalized for easy listing. */
    @Json(name = "supplierName")
    val supplierName: kotlin.String? = null,

    /* Tiered discounts: JSON array of `{min_quantity, discount_percent}`. */
    @Json(name = "volumeDiscountTiers")
    val volumeDiscountTiers: kotlin.Any? = null

) {


}

