/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Single timeline entry aggregated from the contact's activity across all related modules (communications, quotations, orders, invoices, documents).
 *
 * @param date RFC3339 UTC timestamp for sorting.
 * @param id Source record id (stringified).
 * @param title 
 * @param type Source module: communication | quotation | order | invoice | attachment.
 * @param detail 
 * @param status 
 */


data class TimelineEvent (

    /* RFC3339 UTC timestamp for sorting. */
    @Json(name = "date")
    val date: kotlin.String,

    /* Source record id (stringified). */
    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    /* Source module: communication | quotation | order | invoice | attachment. */
    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "detail")
    val detail: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null

) {


}

