/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param backupCodes 
 * @param qrCodeUrl 
 * @param secret 
 */


data class TotpSetupResponse (

    @Json(name = "backup_codes")
    val backupCodes: kotlin.collections.List<kotlin.String>,

    @Json(name = "qr_code_url")
    val qrCodeUrl: kotlin.String,

    @Json(name = "secret")
    val secret: kotlin.String

) {


}

