/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.AssignmentStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param assignedBy 
 * @param createdAt 
 * @param deletedAt 
 * @param dueDate 
 * @param employeeId 
 * @param id 
 * @param notes 
 * @param status 
 * @param tenantId 
 * @param trainingId 
 * @param updatedAt 
 */


data class TrainingAssignment (

    @Json(name = "assignedBy")
    val assignedBy: java.util.UUID? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "deletedAt")
    val deletedAt: java.time.OffsetDateTime? = null,

    @Json(name = "dueDate")
    val dueDate: java.time.LocalDate? = null,

    @Json(name = "employeeId")
    val employeeId: java.util.UUID? = null,

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "notes")
    val notes: kotlin.String? = null,

    @Json(name = "status")
    val status: AssignmentStatus? = null,

    @Json(name = "tenantId")
    val tenantId: java.util.UUID? = null,

    @Json(name = "trainingId")
    val trainingId: java.util.UUID? = null,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

