/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.VatItem

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param inputTaxItems 
 * @param outputTaxItems 
 * @param totalInputTax 
 * @param totalOutputTax 
 * @param vatDue 
 */


data class VatSummary (

    @Json(name = "input_tax_items")
    val inputTaxItems: kotlin.collections.List<VatItem>,

    @Json(name = "output_tax_items")
    val outputTaxItems: kotlin.collections.List<VatItem>,

    @Json(name = "total_input_tax")
    val totalInputTax: kotlin.String,

    @Json(name = "total_output_tax")
    val totalOutputTax: kotlin.String,

    @Json(name = "vat_due")
    val vatDue: kotlin.String

) {


}

