/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One action inside a workflow. Only `email` is supported for now.
 *
 * @param actionType 
 * @param body 
 * @param subject 
 */


data class WorkflowAction (

    @Json(name = "action_type")
    val actionType: kotlin.String,

    @Json(name = "body")
    val body: kotlin.String? = null,

    @Json(name = "subject")
    val subject: kotlin.String? = null

) {


}

