/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.PayrollSummaryItem

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param avgEmployeeCount 
 * @param months 
 * @param year 
 * @param yearlyEmployerCost 
 * @param yearlyGross 
 * @param yearlyNet 
 */


data class YearlyPayrollSummary (

    @Json(name = "avg_employee_count")
    val avgEmployeeCount: kotlin.Int,

    @Json(name = "months")
    val months: kotlin.collections.List<PayrollSummaryItem>,

    @Json(name = "year")
    val year: kotlin.Int,

    @Json(name = "yearly_employer_cost")
    val yearlyEmployerCost: kotlin.String,

    @Json(name = "yearly_gross")
    val yearlyGross: kotlin.String,

    @Json(name = "yearly_net")
    val yearlyNet: kotlin.String

) {


}

