/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import org.openapitools.client.models.Attachment
import org.openapitools.client.models.AttachmentVersion
import org.openapitools.client.models.NewVersionRequest
import org.openapitools.client.models.PluginError

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

open class AttachmentVersionApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://demo.simplebilly.com")
        }
    }

    /**
     * POST /api/v1/attachments/{attachment_id}/versions
     * 
     * 
     * @param attachmentId 
     * @param newVersionRequest 
     * @return AttachmentVersion
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createAttachmentVersion(attachmentId: java.util.UUID, newVersionRequest: NewVersionRequest) : AttachmentVersion {
        val localVarResponse = createAttachmentVersionWithHttpInfo(attachmentId = attachmentId, newVersionRequest = newVersionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AttachmentVersion
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/attachments/{attachment_id}/versions
     * 
     * 
     * @param attachmentId 
     * @param newVersionRequest 
     * @return ApiResponse<AttachmentVersion?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createAttachmentVersionWithHttpInfo(attachmentId: java.util.UUID, newVersionRequest: NewVersionRequest) : ApiResponse<AttachmentVersion?> {
        val localVariableConfig = createAttachmentVersionRequestConfig(attachmentId = attachmentId, newVersionRequest = newVersionRequest)

        return request<NewVersionRequest, AttachmentVersion>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createAttachmentVersion
     *
     * @param attachmentId 
     * @param newVersionRequest 
     * @return RequestConfig
     */
    fun createAttachmentVersionRequestConfig(attachmentId: java.util.UUID, newVersionRequest: NewVersionRequest) : RequestConfig<NewVersionRequest> {
        val localVariableBody = newVersionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/attachments/{attachment_id}/versions".replace("{"+"attachment_id"+"}", encodeURIComponent(attachmentId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/attachments/{attachment_id}/versions
     * 
     * 
     * @param attachmentId 
     * @return kotlin.collections.List<AttachmentVersion>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listAttachmentVersions(attachmentId: java.util.UUID) : kotlin.collections.List<AttachmentVersion> {
        val localVarResponse = listAttachmentVersionsWithHttpInfo(attachmentId = attachmentId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<AttachmentVersion>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/attachments/{attachment_id}/versions
     * 
     * 
     * @param attachmentId 
     * @return ApiResponse<kotlin.collections.List<AttachmentVersion>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listAttachmentVersionsWithHttpInfo(attachmentId: java.util.UUID) : ApiResponse<kotlin.collections.List<AttachmentVersion>?> {
        val localVariableConfig = listAttachmentVersionsRequestConfig(attachmentId = attachmentId)

        return request<Unit, kotlin.collections.List<AttachmentVersion>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listAttachmentVersions
     *
     * @param attachmentId 
     * @return RequestConfig
     */
    fun listAttachmentVersionsRequestConfig(attachmentId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/attachments/{attachment_id}/versions".replace("{"+"attachment_id"+"}", encodeURIComponent(attachmentId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/attachments/{attachment_id}/versions/{version_id}/restore
     * 
     * 
     * @param attachmentId 
     * @param versionId 
     * @return Attachment
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun restoreAttachmentVersion(attachmentId: java.util.UUID, versionId: java.util.UUID) : Attachment {
        val localVarResponse = restoreAttachmentVersionWithHttpInfo(attachmentId = attachmentId, versionId = versionId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Attachment
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/attachments/{attachment_id}/versions/{version_id}/restore
     * 
     * 
     * @param attachmentId 
     * @param versionId 
     * @return ApiResponse<Attachment?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun restoreAttachmentVersionWithHttpInfo(attachmentId: java.util.UUID, versionId: java.util.UUID) : ApiResponse<Attachment?> {
        val localVariableConfig = restoreAttachmentVersionRequestConfig(attachmentId = attachmentId, versionId = versionId)

        return request<Unit, Attachment>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation restoreAttachmentVersion
     *
     * @param attachmentId 
     * @param versionId 
     * @return RequestConfig
     */
    fun restoreAttachmentVersionRequestConfig(attachmentId: java.util.UUID, versionId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/attachments/{attachment_id}/versions/{version_id}/restore".replace("{"+"attachment_id"+"}", encodeURIComponent(attachmentId.toString())).replace("{"+"version_id"+"}", encodeURIComponent(versionId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
