/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import org.openapitools.client.models.EmailTemplate
import org.openapitools.client.models.EmailTemplateCreate
import org.openapitools.client.models.EmailTemplateUpdate
import org.openapitools.client.models.PluginError

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

open class EmailTemplateApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://demo.simplebilly.com")
        }
    }

    /**
     * POST /api/v1/email-templates
     * 
     * 
     * @param emailTemplateCreate 
     * @return EmailTemplate
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createEmailTemplate(emailTemplateCreate: EmailTemplateCreate) : EmailTemplate {
        val localVarResponse = createEmailTemplateWithHttpInfo(emailTemplateCreate = emailTemplateCreate)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as EmailTemplate
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/email-templates
     * 
     * 
     * @param emailTemplateCreate 
     * @return ApiResponse<EmailTemplate?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createEmailTemplateWithHttpInfo(emailTemplateCreate: EmailTemplateCreate) : ApiResponse<EmailTemplate?> {
        val localVariableConfig = createEmailTemplateRequestConfig(emailTemplateCreate = emailTemplateCreate)

        return request<EmailTemplateCreate, EmailTemplate>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createEmailTemplate
     *
     * @param emailTemplateCreate 
     * @return RequestConfig
     */
    fun createEmailTemplateRequestConfig(emailTemplateCreate: EmailTemplateCreate) : RequestConfig<EmailTemplateCreate> {
        val localVariableBody = emailTemplateCreate
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/email-templates",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /api/v1/email-templates/{email_template_id}
     * 
     * 
     * @param emailTemplateId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteEmailTemplate(emailTemplateId: kotlin.String) : Unit {
        val localVarResponse = deleteEmailTemplateWithHttpInfo(emailTemplateId = emailTemplateId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /api/v1/email-templates/{email_template_id}
     * 
     * 
     * @param emailTemplateId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteEmailTemplateWithHttpInfo(emailTemplateId: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = deleteEmailTemplateRequestConfig(emailTemplateId = emailTemplateId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteEmailTemplate
     *
     * @param emailTemplateId 
     * @return RequestConfig
     */
    fun deleteEmailTemplateRequestConfig(emailTemplateId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/v1/email-templates/{email_template_id}".replace("{"+"email_template_id"+"}", encodeURIComponent(emailTemplateId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/email-templates/{email_template_id}
     * 
     * 
     * @param emailTemplateId 
     * @return EmailTemplate
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getEmailTemplate(emailTemplateId: kotlin.String) : EmailTemplate {
        val localVarResponse = getEmailTemplateWithHttpInfo(emailTemplateId = emailTemplateId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as EmailTemplate
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/email-templates/{email_template_id}
     * 
     * 
     * @param emailTemplateId 
     * @return ApiResponse<EmailTemplate?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getEmailTemplateWithHttpInfo(emailTemplateId: kotlin.String) : ApiResponse<EmailTemplate?> {
        val localVariableConfig = getEmailTemplateRequestConfig(emailTemplateId = emailTemplateId)

        return request<Unit, EmailTemplate>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getEmailTemplate
     *
     * @param emailTemplateId 
     * @return RequestConfig
     */
    fun getEmailTemplateRequestConfig(emailTemplateId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/email-templates/{email_template_id}".replace("{"+"email_template_id"+"}", encodeURIComponent(emailTemplateId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/email-templates/
     * 
     * 
     * @param page  (optional)
     * @param pageSize  (optional)
     * @param status  (optional)
     * @param search  (optional)
     * @return kotlin.collections.List<EmailTemplate>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listEmailTemplates(page: kotlin.Int? = null, pageSize: kotlin.Int? = null, status: kotlin.String? = null, search: kotlin.String? = null) : kotlin.collections.List<EmailTemplate> {
        val localVarResponse = listEmailTemplatesWithHttpInfo(page = page, pageSize = pageSize, status = status, search = search)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<EmailTemplate>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/email-templates/
     * 
     * 
     * @param page  (optional)
     * @param pageSize  (optional)
     * @param status  (optional)
     * @param search  (optional)
     * @return ApiResponse<kotlin.collections.List<EmailTemplate>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listEmailTemplatesWithHttpInfo(page: kotlin.Int?, pageSize: kotlin.Int?, status: kotlin.String?, search: kotlin.String?) : ApiResponse<kotlin.collections.List<EmailTemplate>?> {
        val localVariableConfig = listEmailTemplatesRequestConfig(page = page, pageSize = pageSize, status = status, search = search)

        return request<Unit, kotlin.collections.List<EmailTemplate>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listEmailTemplates
     *
     * @param page  (optional)
     * @param pageSize  (optional)
     * @param status  (optional)
     * @param search  (optional)
     * @return RequestConfig
     */
    fun listEmailTemplatesRequestConfig(page: kotlin.Int?, pageSize: kotlin.Int?, status: kotlin.String?, search: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (pageSize != null) {
                    put("pageSize", listOf(pageSize.toString()))
                }
                if (status != null) {
                    put("status", listOf(status.toString()))
                }
                if (search != null) {
                    put("search", listOf(search.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/email-templates/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/email-templates/{email_template_id}/render
     * 
     * 
     * @param emailTemplateId 
     * @param body 
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun renderEmailTemplate(emailTemplateId: kotlin.String, body: kotlin.Any) : kotlin.Any {
        val localVarResponse = renderEmailTemplateWithHttpInfo(emailTemplateId = emailTemplateId, body = body)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/email-templates/{email_template_id}/render
     * 
     * 
     * @param emailTemplateId 
     * @param body 
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun renderEmailTemplateWithHttpInfo(emailTemplateId: kotlin.String, body: kotlin.Any) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = renderEmailTemplateRequestConfig(emailTemplateId = emailTemplateId, body = body)

        return request<kotlin.Any, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation renderEmailTemplate
     *
     * @param emailTemplateId 
     * @param body 
     * @return RequestConfig
     */
    fun renderEmailTemplateRequestConfig(emailTemplateId: kotlin.String, body: kotlin.Any) : RequestConfig<kotlin.Any> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/email-templates/{email_template_id}/render".replace("{"+"email_template_id"+"}", encodeURIComponent(emailTemplateId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /api/v1/email-templates/{email_template_id}
     * 
     * 
     * @param emailTemplateId 
     * @param emailTemplateUpdate 
     * @return EmailTemplate
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateEmailTemplate(emailTemplateId: kotlin.String, emailTemplateUpdate: EmailTemplateUpdate) : EmailTemplate {
        val localVarResponse = updateEmailTemplateWithHttpInfo(emailTemplateId = emailTemplateId, emailTemplateUpdate = emailTemplateUpdate)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as EmailTemplate
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /api/v1/email-templates/{email_template_id}
     * 
     * 
     * @param emailTemplateId 
     * @param emailTemplateUpdate 
     * @return ApiResponse<EmailTemplate?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateEmailTemplateWithHttpInfo(emailTemplateId: kotlin.String, emailTemplateUpdate: EmailTemplateUpdate) : ApiResponse<EmailTemplate?> {
        val localVariableConfig = updateEmailTemplateRequestConfig(emailTemplateId = emailTemplateId, emailTemplateUpdate = emailTemplateUpdate)

        return request<EmailTemplateUpdate, EmailTemplate>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateEmailTemplate
     *
     * @param emailTemplateId 
     * @param emailTemplateUpdate 
     * @return RequestConfig
     */
    fun updateEmailTemplateRequestConfig(emailTemplateId: kotlin.String, emailTemplateUpdate: EmailTemplateUpdate) : RequestConfig<EmailTemplateUpdate> {
        val localVariableBody = emailTemplateUpdate
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/api/v1/email-templates/{email_template_id}".replace("{"+"email_template_id"+"}", encodeURIComponent(emailTemplateId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
