/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import org.openapitools.client.models.GewerbesteuerErgebnis

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

open class GewerbesteuerApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://demo.simplebilly.com")
        }
    }

    /**
     * GET /api/v1/bookkeeping/gewerbesteuer
     * 
     * 
     * @param year 
     * @param hebesatz  (optional)
     * @param gewerbeertrag  (optional)
     * @param country  (optional)
     * @param gemeindeschluessel  (optional)
     * @return GewerbesteuerErgebnis
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun gewerbesteuerApi(year: kotlin.Int, hebesatz: kotlin.String? = null, gewerbeertrag: kotlin.String? = null, country: kotlin.String? = null, gemeindeschluessel: kotlin.String? = null) : GewerbesteuerErgebnis {
        val localVarResponse = gewerbesteuerApiWithHttpInfo(year = year, hebesatz = hebesatz, gewerbeertrag = gewerbeertrag, country = country, gemeindeschluessel = gemeindeschluessel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GewerbesteuerErgebnis
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/bookkeeping/gewerbesteuer
     * 
     * 
     * @param year 
     * @param hebesatz  (optional)
     * @param gewerbeertrag  (optional)
     * @param country  (optional)
     * @param gemeindeschluessel  (optional)
     * @return ApiResponse<GewerbesteuerErgebnis?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun gewerbesteuerApiWithHttpInfo(year: kotlin.Int, hebesatz: kotlin.String?, gewerbeertrag: kotlin.String?, country: kotlin.String?, gemeindeschluessel: kotlin.String?) : ApiResponse<GewerbesteuerErgebnis?> {
        val localVariableConfig = gewerbesteuerApiRequestConfig(year = year, hebesatz = hebesatz, gewerbeertrag = gewerbeertrag, country = country, gemeindeschluessel = gemeindeschluessel)

        return request<Unit, GewerbesteuerErgebnis>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation gewerbesteuerApi
     *
     * @param year 
     * @param hebesatz  (optional)
     * @param gewerbeertrag  (optional)
     * @param country  (optional)
     * @param gemeindeschluessel  (optional)
     * @return RequestConfig
     */
    fun gewerbesteuerApiRequestConfig(year: kotlin.Int, hebesatz: kotlin.String?, gewerbeertrag: kotlin.String?, country: kotlin.String?, gemeindeschluessel: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("year", listOf(year.toString()))
                if (hebesatz != null) {
                    put("hebesatz", listOf(hebesatz.toString()))
                }
                if (gewerbeertrag != null) {
                    put("gewerbeertrag", listOf(gewerbeertrag.toString()))
                }
                if (country != null) {
                    put("country", listOf(country.toString()))
                }
                if (gemeindeschluessel != null) {
                    put("gemeindeschluessel", listOf(gemeindeschluessel.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/bookkeeping/gewerbesteuer",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
